// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type BlockstorageInitParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (Boolean) Whether this volume can be used as a boot volume for an arubacloud_cloudserver. Must be true when image is set.
	// Whether this volume can be used as a boot volume for an `arubacloud_cloudserver`. Must be `true` when `image` is set.
	Bootable *bool `json:"bootable,omitempty" tf:"bootable,omitempty"`

	// (String) Image ID to use when creating a bootable volume. Required when bootable is true. See the available images.
	// Image ID to use when creating a bootable volume. Required when `bootable` is `true`. See the [available images](https://api.arubacloud.com/docs/metadata/#cloud-server-bootvolume).
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the block storage volume.
	// Display name for the block storage volume.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Number) Size of the block storage volume in GiB. Must be a positive integer.
	// Size of the block storage volume in GiB. Must be a positive integer.
	SizeGb *float64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// created.)
	// Storage type. Accepted values: `Standard`, `Performance`. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	// Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type BlockstorageObservation struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (Boolean) Whether this volume can be used as a boot volume for an arubacloud_cloudserver. Must be true when image is set.
	// Whether this volume can be used as a boot volume for an `arubacloud_cloudserver`. Must be `true` when `image` is set.
	Bootable *bool `json:"bootable,omitempty" tf:"bootable,omitempty"`

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Image ID to use when creating a bootable volume. Required when bootable is true. See the available images.
	// Image ID to use when creating a bootable volume. Required when `bootable` is `true`. See the [available images](https://api.arubacloud.com/docs/metadata/#cloud-server-bootvolume).
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the block storage volume.
	// Display name for the block storage volume.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Number) Size of the block storage volume in GiB. Must be a positive integer.
	// Size of the block storage volume in GiB. Must be a positive integer.
	SizeGb *float64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// created.)
	// Storage type. Accepted values: `Standard`, `Performance`. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources.
	// Computed by the API. Full resource URI used as a reference value in other resources.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// (String) Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	// Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type BlockstorageParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	// +kubebuilder:validation:Optional
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (Boolean) Whether this volume can be used as a boot volume for an arubacloud_cloudserver. Must be true when image is set.
	// Whether this volume can be used as a boot volume for an `arubacloud_cloudserver`. Must be `true` when `image` is set.
	// +kubebuilder:validation:Optional
	Bootable *bool `json:"bootable,omitempty" tf:"bootable,omitempty"`

	// (String) Image ID to use when creating a bootable volume. Required when bootable is true. See the available images.
	// Image ID to use when creating a bootable volume. Required when `bootable` is `true`. See the [available images](https://api.arubacloud.com/docs/metadata/#cloud-server-bootvolume).
	// +kubebuilder:validation:Optional
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the block storage volume.
	// Display name for the block storage volume.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Number) Size of the block storage volume in GiB. Must be a positive integer.
	// Size of the block storage volume in GiB. Must be a positive integer.
	// +kubebuilder:validation:Optional
	SizeGb *float64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// created.)
	// Storage type. Accepted values: `Standard`, `Performance`. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	// Availability zone within the region. If omitted the volume is regional (accessible across all zones).
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// BlockstorageSpec defines the desired state of Blockstorage
type BlockstorageSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BlockstorageParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BlockstorageInitParameters `json:"initProvider,omitempty"`
}

// BlockstorageStatus defines the observed state of Blockstorage.
type BlockstorageStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               BlockstorageObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Blockstorage is the Schema for the Blockstorages API. Manages an ArubaCloud Block Storage volume.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type Blockstorage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.billingPeriod) || (has(self.initProvider) && has(self.initProvider.billingPeriod))",message="spec.forProvider.billingPeriod is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sizeGb) || (has(self.initProvider) && has(self.initProvider.sizeGb))",message="spec.forProvider.sizeGb is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   BlockstorageSpec   `json:"spec"`
	Status BlockstorageStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BlockstorageList contains a list of Blockstorages
type BlockstorageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Blockstorage `json:"items"`
}

// Repository type metadata.
var (
	Blockstorage_Kind             = "Blockstorage"
	Blockstorage_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Blockstorage_Kind}.String()
	Blockstorage_KindAPIVersion   = Blockstorage_Kind + "." + CRDGroupVersion.String()
	Blockstorage_GroupVersionKind = CRDGroupVersion.WithKind(Blockstorage_Kind)
)

func init() {
	SchemeBuilder.Register(&Blockstorage{}, &BlockstorageList{})
}
