// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ContainerregistryInitParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// Bergamo). See the available locations and zones.
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the container registry.
	// Display name for the container registry.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network resources attached to the registry. (see below for nested schema)
	Network *ContainerregistryNetworkInitParameters `json:"network,omitempty" tf:"network,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Attributes) Registry configuration settings. Required because admin_user is mandatory. (see below for nested schema)
	Settings *ContainerregistrySettingsInitParameters `json:"settings,omitempty" tf:"settings,omitempty"`

	// (Attributes) Block storage volume that backs the registry image store. (see below for nested schema)
	Storage *ContainerregistryStorageInitParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type ContainerregistryNetworkInitParameters struct {

	// (String) URI of the Elastic IP that exposes the registry endpoint (e.g., arubacloud_elasticip.example.uri).
	// URI of the Elastic IP that exposes the registry endpoint (e.g., `arubacloud_elasticip.example.uri`).
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Elasticip
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	PublicIPURIRef *string `json:"publicIpUriRef,omitempty" tf:"public_ip_uri_ref,omitempty"`

	// Reference to a Elasticip in arubacloud to populate publicIpUriRef.
	// +kubebuilder:validation:Optional
	PublicIPURIRefRef *v2.NamespacedReference `json:"publicIpUriRefRef,omitempty" tf:"-"`

	// Selector for a Elasticip in arubacloud to populate publicIpUriRef.
	// +kubebuilder:validation:Optional
	PublicIPURIRefSelector *v2.NamespacedSelector `json:"publicIpUriRefSelector,omitempty" tf:"-"`

	// (String) URI of the security group controlling registry traffic (e.g., arubacloud_securitygroup.example.uri).
	// URI of the security group controlling registry traffic (e.g., `arubacloud_securitygroup.example.uri`).
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Securitygroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	SecurityGroupURIRef *string `json:"securityGroupUriRef,omitempty" tf:"security_group_uri_ref,omitempty"`

	// Reference to a Securitygroup in arubacloud to populate securityGroupUriRef.
	// +kubebuilder:validation:Optional
	SecurityGroupURIRefRef *v2.NamespacedReference `json:"securityGroupUriRefRef,omitempty" tf:"-"`

	// Selector for a Securitygroup in arubacloud to populate securityGroupUriRef.
	// +kubebuilder:validation:Optional
	SecurityGroupURIRefSelector *v2.NamespacedSelector `json:"securityGroupUriRefSelector,omitempty" tf:"-"`

	// (String) URI of the subnet within the VPC (e.g., arubacloud_subnet.example.uri).
	// URI of the subnet within the VPC (e.g., `arubacloud_subnet.example.uri`).
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	SubnetURIRef *string `json:"subnetUriRef,omitempty" tf:"subnet_uri_ref,omitempty"`

	// Reference to a Subnet in arubacloud to populate subnetUriRef.
	// +kubebuilder:validation:Optional
	SubnetURIRefRef *v2.NamespacedReference `json:"subnetUriRefRef,omitempty" tf:"-"`

	// Selector for a Subnet in arubacloud to populate subnetUriRef.
	// +kubebuilder:validation:Optional
	SubnetURIRefSelector *v2.NamespacedSelector `json:"subnetUriRefSelector,omitempty" tf:"-"`

	// (String) URI of the VPC that hosts the registry (e.g., arubacloud_vpc.example.uri).
	// URI of the VPC that hosts the registry (e.g., `arubacloud_vpc.example.uri`).
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.VPC
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`

	// Reference to a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefRef *v2.NamespacedReference `json:"vpcUriRefRef,omitempty" tf:"-"`

	// Selector for a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefSelector *v2.NamespacedSelector `json:"vpcUriRefSelector,omitempty" tf:"-"`
}

type ContainerregistryNetworkObservation struct {

	// (String) URI of the Elastic IP that exposes the registry endpoint (e.g., arubacloud_elasticip.example.uri).
	// URI of the Elastic IP that exposes the registry endpoint (e.g., `arubacloud_elasticip.example.uri`).
	PublicIPURIRef *string `json:"publicIpUriRef,omitempty" tf:"public_ip_uri_ref,omitempty"`

	// (String) URI of the security group controlling registry traffic (e.g., arubacloud_securitygroup.example.uri).
	// URI of the security group controlling registry traffic (e.g., `arubacloud_securitygroup.example.uri`).
	SecurityGroupURIRef *string `json:"securityGroupUriRef,omitempty" tf:"security_group_uri_ref,omitempty"`

	// (String) URI of the subnet within the VPC (e.g., arubacloud_subnet.example.uri).
	// URI of the subnet within the VPC (e.g., `arubacloud_subnet.example.uri`).
	SubnetURIRef *string `json:"subnetUriRef,omitempty" tf:"subnet_uri_ref,omitempty"`

	// (String) URI of the VPC that hosts the registry (e.g., arubacloud_vpc.example.uri).
	// URI of the VPC that hosts the registry (e.g., `arubacloud_vpc.example.uri`).
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`
}

type ContainerregistryNetworkParameters struct {

	// (String) URI of the Elastic IP that exposes the registry endpoint (e.g., arubacloud_elasticip.example.uri).
	// URI of the Elastic IP that exposes the registry endpoint (e.g., `arubacloud_elasticip.example.uri`).
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Elasticip
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	PublicIPURIRef *string `json:"publicIpUriRef,omitempty" tf:"public_ip_uri_ref,omitempty"`

	// Reference to a Elasticip in arubacloud to populate publicIpUriRef.
	// +kubebuilder:validation:Optional
	PublicIPURIRefRef *v2.NamespacedReference `json:"publicIpUriRefRef,omitempty" tf:"-"`

	// Selector for a Elasticip in arubacloud to populate publicIpUriRef.
	// +kubebuilder:validation:Optional
	PublicIPURIRefSelector *v2.NamespacedSelector `json:"publicIpUriRefSelector,omitempty" tf:"-"`

	// (String) URI of the security group controlling registry traffic (e.g., arubacloud_securitygroup.example.uri).
	// URI of the security group controlling registry traffic (e.g., `arubacloud_securitygroup.example.uri`).
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Securitygroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	SecurityGroupURIRef *string `json:"securityGroupUriRef,omitempty" tf:"security_group_uri_ref,omitempty"`

	// Reference to a Securitygroup in arubacloud to populate securityGroupUriRef.
	// +kubebuilder:validation:Optional
	SecurityGroupURIRefRef *v2.NamespacedReference `json:"securityGroupUriRefRef,omitempty" tf:"-"`

	// Selector for a Securitygroup in arubacloud to populate securityGroupUriRef.
	// +kubebuilder:validation:Optional
	SecurityGroupURIRefSelector *v2.NamespacedSelector `json:"securityGroupUriRefSelector,omitempty" tf:"-"`

	// (String) URI of the subnet within the VPC (e.g., arubacloud_subnet.example.uri).
	// URI of the subnet within the VPC (e.g., `arubacloud_subnet.example.uri`).
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	SubnetURIRef *string `json:"subnetUriRef,omitempty" tf:"subnet_uri_ref,omitempty"`

	// Reference to a Subnet in arubacloud to populate subnetUriRef.
	// +kubebuilder:validation:Optional
	SubnetURIRefRef *v2.NamespacedReference `json:"subnetUriRefRef,omitempty" tf:"-"`

	// Selector for a Subnet in arubacloud to populate subnetUriRef.
	// +kubebuilder:validation:Optional
	SubnetURIRefSelector *v2.NamespacedSelector `json:"subnetUriRefSelector,omitempty" tf:"-"`

	// (String) URI of the VPC that hosts the registry (e.g., arubacloud_vpc.example.uri).
	// URI of the VPC that hosts the registry (e.g., `arubacloud_vpc.example.uri`).
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.VPC
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`

	// Reference to a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefRef *v2.NamespacedReference `json:"vpcUriRefRef,omitempty" tf:"-"`

	// Selector for a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefSelector *v2.NamespacedSelector `json:"vpcUriRefSelector,omitempty" tf:"-"`
}

type ContainerregistryObservation struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bergamo). See the available locations and zones.
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the container registry.
	// Display name for the container registry.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network resources attached to the registry. (see below for nested schema)
	Network *ContainerregistryNetworkObservation `json:"network,omitempty" tf:"network,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Registry configuration settings. Required because admin_user is mandatory. (see below for nested schema)
	Settings *ContainerregistrySettingsObservation `json:"settings,omitempty" tf:"settings,omitempty"`

	// (Attributes) Block storage volume that backs the registry image store. (see below for nested schema)
	Storage *ContainerregistryStorageObservation `json:"storage,omitempty" tf:"storage,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources.
	// Computed by the API. Full resource URI used as a reference value in other resources.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

type ContainerregistryParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	// +kubebuilder:validation:Optional
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// Bergamo). See the available locations and zones.
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the container registry.
	// Display name for the container registry.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network resources attached to the registry. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Network *ContainerregistryNetworkParameters `json:"network,omitempty" tf:"network,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Attributes) Registry configuration settings. Required because admin_user is mandatory. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Settings *ContainerregistrySettingsParameters `json:"settings,omitempty" tf:"settings,omitempty"`

	// (Attributes) Block storage volume that backs the registry image store. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Storage *ContainerregistryStorageParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type ContainerregistrySettingsInitParameters struct {

	// (String) Administrator username for the registry. Must not be "admin" (reserved by the API).
	// Administrator username for the registry. Must not be `"admin"` (reserved by the API).
	AdminUser *string `json:"adminUser,omitempty" tf:"admin_user,omitempty"`

	// (String) Concurrency tier that determines how many simultaneous push/pull sessions are supported. Accepted values: Small, Medium, HighPerf.
	// Concurrency tier that determines how many simultaneous push/pull sessions are supported. Accepted values: `Small`, `Medium`, `HighPerf`.
	ConcurrentUsersFlavor *string `json:"concurrentUsersFlavor,omitempty" tf:"concurrent_users_flavor,omitempty"`
}

type ContainerregistrySettingsObservation struct {

	// (String) Administrator username for the registry. Must not be "admin" (reserved by the API).
	// Administrator username for the registry. Must not be `"admin"` (reserved by the API).
	AdminUser *string `json:"adminUser,omitempty" tf:"admin_user,omitempty"`

	// (String) Concurrency tier that determines how many simultaneous push/pull sessions are supported. Accepted values: Small, Medium, HighPerf.
	// Concurrency tier that determines how many simultaneous push/pull sessions are supported. Accepted values: `Small`, `Medium`, `HighPerf`.
	ConcurrentUsersFlavor *string `json:"concurrentUsersFlavor,omitempty" tf:"concurrent_users_flavor,omitempty"`
}

type ContainerregistrySettingsParameters struct {

	// (String) Administrator username for the registry. Must not be "admin" (reserved by the API).
	// Administrator username for the registry. Must not be `"admin"` (reserved by the API).
	// +kubebuilder:validation:Optional
	AdminUser *string `json:"adminUser" tf:"admin_user,omitempty"`

	// (String) Concurrency tier that determines how many simultaneous push/pull sessions are supported. Accepted values: Small, Medium, HighPerf.
	// Concurrency tier that determines how many simultaneous push/pull sessions are supported. Accepted values: `Small`, `Medium`, `HighPerf`.
	// +kubebuilder:validation:Optional
	ConcurrentUsersFlavor *string `json:"concurrentUsersFlavor,omitempty" tf:"concurrent_users_flavor,omitempty"`
}

type ContainerregistryStorageInitParameters struct {

	// (String) URI of the block storage volume (e.g., arubacloud_blockstorage.example.uri).
	// URI of the block storage volume (e.g., `arubacloud_blockstorage.example.uri`).
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Blockstorage
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	BlockStorageURIRef *string `json:"blockStorageUriRef,omitempty" tf:"block_storage_uri_ref,omitempty"`

	// Reference to a Blockstorage in arubacloud to populate blockStorageUriRef.
	// +kubebuilder:validation:Optional
	BlockStorageURIRefRef *v2.NamespacedReference `json:"blockStorageUriRefRef,omitempty" tf:"-"`

	// Selector for a Blockstorage in arubacloud to populate blockStorageUriRef.
	// +kubebuilder:validation:Optional
	BlockStorageURIRefSelector *v2.NamespacedSelector `json:"blockStorageUriRefSelector,omitempty" tf:"-"`
}

type ContainerregistryStorageObservation struct {

	// (String) URI of the block storage volume (e.g., arubacloud_blockstorage.example.uri).
	// URI of the block storage volume (e.g., `arubacloud_blockstorage.example.uri`).
	BlockStorageURIRef *string `json:"blockStorageUriRef,omitempty" tf:"block_storage_uri_ref,omitempty"`
}

type ContainerregistryStorageParameters struct {

	// (String) URI of the block storage volume (e.g., arubacloud_blockstorage.example.uri).
	// URI of the block storage volume (e.g., `arubacloud_blockstorage.example.uri`).
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Blockstorage
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	BlockStorageURIRef *string `json:"blockStorageUriRef,omitempty" tf:"block_storage_uri_ref,omitempty"`

	// Reference to a Blockstorage in arubacloud to populate blockStorageUriRef.
	// +kubebuilder:validation:Optional
	BlockStorageURIRefRef *v2.NamespacedReference `json:"blockStorageUriRefRef,omitempty" tf:"-"`

	// Selector for a Blockstorage in arubacloud to populate blockStorageUriRef.
	// +kubebuilder:validation:Optional
	BlockStorageURIRefSelector *v2.NamespacedSelector `json:"blockStorageUriRefSelector,omitempty" tf:"-"`
}

// ContainerregistrySpec defines the desired state of Containerregistry
type ContainerregistrySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ContainerregistryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ContainerregistryInitParameters `json:"initProvider,omitempty"`
}

// ContainerregistryStatus defines the observed state of Containerregistry.
type ContainerregistryStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ContainerregistryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Containerregistry is the Schema for the Containerregistrys API. Manages an ArubaCloud Container Registry — a private OCI-compatible image registry.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type Containerregistry struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.network) || (has(self.initProvider) && has(self.initProvider.network))",message="spec.forProvider.network is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.settings) || (has(self.initProvider) && has(self.initProvider.settings))",message="spec.forProvider.settings is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storage) || (has(self.initProvider) && has(self.initProvider.storage))",message="spec.forProvider.storage is a required parameter"
	Spec   ContainerregistrySpec   `json:"spec"`
	Status ContainerregistryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ContainerregistryList contains a list of Containerregistrys
type ContainerregistryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Containerregistry `json:"items"`
}

// Repository type metadata.
var (
	Containerregistry_Kind             = "Containerregistry"
	Containerregistry_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Containerregistry_Kind}.String()
	Containerregistry_KindAPIVersion   = Containerregistry_Kind + "." + CRDGroupVersion.String()
	Containerregistry_GroupVersionKind = CRDGroupVersion.WithKind(Containerregistry_Kind)
)

func init() {
	SchemeBuilder.Register(&Containerregistry{}, &ContainerregistryList{})
}
