// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CloudserverInitParameters struct {

	// Bergamo). See the available locations and zones. Changing this value forces a new resource.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). Changing this value forces a new resource.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the CloudServer. Changing this value forces a new resource.
	// Display name for the CloudServer. Changing this value forces a new resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the CloudServer. (see below for nested schema)
	Network *NetworkInitParameters `json:"network,omitempty" tf:"network,omitempty"`

	// (String) ID of the project that owns this resource. Changing this value forces a new resource.
	// ID of the project that owns this resource. Changing this value forces a new resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Attributes) Compute and access settings for the CloudServer. (see below for nested schema)
	Settings *SettingsInitParameters `json:"settings,omitempty" tf:"settings,omitempty"`

	// (Attributes) Storage configuration for the CloudServer. (see below for nested schema)
	Storage *StorageInitParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation. Changing this value forces a new resource.
	// List of string tags attached to the resource for filtering and organisation. Changing this value forces a new resource.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// 1). See available zones. Changing this value forces a new resource.
	// Availability zone within the region (e.g., `ITBG-1`). See [available zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). Changing this value forces a new resource.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type CloudserverObservation struct {

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bergamo). See the available locations and zones. Changing this value forces a new resource.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). Changing this value forces a new resource.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the CloudServer. Changing this value forces a new resource.
	// Display name for the CloudServer. Changing this value forces a new resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the CloudServer. (see below for nested schema)
	Network *NetworkObservation `json:"network,omitempty" tf:"network,omitempty"`

	// (String) ID of the project that owns this resource. Changing this value forces a new resource.
	// ID of the project that owns this resource. Changing this value forces a new resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Compute and access settings for the CloudServer. (see below for nested schema)
	Settings *SettingsObservation `json:"settings,omitempty" tf:"settings,omitempty"`

	// (Attributes) Storage configuration for the CloudServer. (see below for nested schema)
	Storage *StorageObservation `json:"storage,omitempty" tf:"storage,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation. Changing this value forces a new resource.
	// List of string tags attached to the resource for filtering and organisation. Changing this value forces a new resource.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a *_uri_ref attribute).
	// Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a `*_uri_ref` attribute).
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// 1). See available zones. Changing this value forces a new resource.
	// Availability zone within the region (e.g., `ITBG-1`). See [available zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). Changing this value forces a new resource.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type CloudserverParameters struct {

	// Bergamo). See the available locations and zones. Changing this value forces a new resource.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). Changing this value forces a new resource.
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the CloudServer. Changing this value forces a new resource.
	// Display name for the CloudServer. Changing this value forces a new resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the CloudServer. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Network *NetworkParameters `json:"network,omitempty" tf:"network,omitempty"`

	// (String) ID of the project that owns this resource. Changing this value forces a new resource.
	// ID of the project that owns this resource. Changing this value forces a new resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Attributes) Compute and access settings for the CloudServer. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Settings *SettingsParameters `json:"settings,omitempty" tf:"settings,omitempty"`

	// (Attributes) Storage configuration for the CloudServer. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Storage *StorageParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation. Changing this value forces a new resource.
	// List of string tags attached to the resource for filtering and organisation. Changing this value forces a new resource.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// 1). See available zones. Changing this value forces a new resource.
	// Availability zone within the region (e.g., `ITBG-1`). See [available zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). Changing this value forces a new resource.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type NetworkInitParameters struct {

	// (String) URI of an Elastic IP to associate with this CloudServer. Reference the uri attribute of an arubacloud_elasticip resource. Optional — omit to use a dynamic IP. Changing this value forces a new resource.
	// URI of an Elastic IP to associate with this CloudServer. Reference the `uri` attribute of an `arubacloud_elasticip` resource. Optional — omit to use a dynamic IP. Changing this value forces a new resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Elasticip
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	ElasticIPURIRef *string `json:"elasticIpUriRef,omitempty" tf:"elastic_ip_uri_ref,omitempty"`

	// Reference to a Elasticip in arubacloud to populate elasticIpUriRef.
	// +kubebuilder:validation:Optional
	ElasticIPURIRefRef *v2.NamespacedReference `json:"elasticIpUriRefRef,omitempty" tf:"-"`

	// Selector for a Elasticip in arubacloud to populate elasticIpUriRef.
	// +kubebuilder:validation:Optional
	ElasticIPURIRefSelector *v2.NamespacedSelector `json:"elasticIpUriRefSelector,omitempty" tf:"-"`

	// (List of String) List of security group URIs to apply to this CloudServer. Reference the uri attribute of each arubacloud_securitygroup resource. Changing this value forces a new resource.
	// List of security group URIs to apply to this CloudServer. Reference the `uri` attribute of each `arubacloud_securitygroup` resource. Changing this value forces a new resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Securitygroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	SecuritygroupURIRefs []*string `json:"securitygroupUriRefs,omitempty" tf:"securitygroup_uri_refs,omitempty"`

	// References to Securitygroup in arubacloud to populate securitygroupUriRefs.
	// +kubebuilder:validation:Optional
	SecuritygroupURIRefsRefs []v2.NamespacedReference `json:"securitygroupUriRefsRefs,omitempty" tf:"-"`

	// Selector for a list of Securitygroup in arubacloud to populate securitygroupUriRefs.
	// +kubebuilder:validation:Optional
	SecuritygroupURIRefsSelector *v2.NamespacedSelector `json:"securitygroupUriRefsSelector,omitempty" tf:"-"`

	// (List of String) List of subnet URIs to attach this CloudServer to. Reference the uri attribute of each arubacloud_subnet resource. Changing this value forces a new resource.
	// List of subnet URIs to attach this CloudServer to. Reference the `uri` attribute of each `arubacloud_subnet` resource. Changing this value forces a new resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	SubnetURIRefs []*string `json:"subnetUriRefs,omitempty" tf:"subnet_uri_refs,omitempty"`

	// References to Subnet in arubacloud to populate subnetUriRefs.
	// +kubebuilder:validation:Optional
	SubnetURIRefsRefs []v2.NamespacedReference `json:"subnetUriRefsRefs,omitempty" tf:"-"`

	// Selector for a list of Subnet in arubacloud to populate subnetUriRefs.
	// +kubebuilder:validation:Optional
	SubnetURIRefsSelector *v2.NamespacedSelector `json:"subnetUriRefsSelector,omitempty" tf:"-"`

	// (String) URI of the VPC to attach this CloudServer to. Reference the uri attribute of an arubacloud_vpc resource. Changing this value forces a new resource.
	// URI of the VPC to attach this CloudServer to. Reference the `uri` attribute of an `arubacloud_vpc` resource. Changing this value forces a new resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.VPC
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`

	// Reference to a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefRef *v2.NamespacedReference `json:"vpcUriRefRef,omitempty" tf:"-"`

	// Selector for a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefSelector *v2.NamespacedSelector `json:"vpcUriRefSelector,omitempty" tf:"-"`
}

type NetworkObservation struct {

	// (String) URI of an Elastic IP to associate with this CloudServer. Reference the uri attribute of an arubacloud_elasticip resource. Optional — omit to use a dynamic IP. Changing this value forces a new resource.
	// URI of an Elastic IP to associate with this CloudServer. Reference the `uri` attribute of an `arubacloud_elasticip` resource. Optional — omit to use a dynamic IP. Changing this value forces a new resource.
	ElasticIPURIRef *string `json:"elasticIpUriRef,omitempty" tf:"elastic_ip_uri_ref,omitempty"`

	// (List of String) List of security group URIs to apply to this CloudServer. Reference the uri attribute of each arubacloud_securitygroup resource. Changing this value forces a new resource.
	// List of security group URIs to apply to this CloudServer. Reference the `uri` attribute of each `arubacloud_securitygroup` resource. Changing this value forces a new resource.
	SecuritygroupURIRefs []*string `json:"securitygroupUriRefs,omitempty" tf:"securitygroup_uri_refs,omitempty"`

	// (List of String) List of subnet URIs to attach this CloudServer to. Reference the uri attribute of each arubacloud_subnet resource. Changing this value forces a new resource.
	// List of subnet URIs to attach this CloudServer to. Reference the `uri` attribute of each `arubacloud_subnet` resource. Changing this value forces a new resource.
	SubnetURIRefs []*string `json:"subnetUriRefs,omitempty" tf:"subnet_uri_refs,omitempty"`

	// (String) URI of the VPC to attach this CloudServer to. Reference the uri attribute of an arubacloud_vpc resource. Changing this value forces a new resource.
	// URI of the VPC to attach this CloudServer to. Reference the `uri` attribute of an `arubacloud_vpc` resource. Changing this value forces a new resource.
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`
}

type NetworkParameters struct {

	// (String) URI of an Elastic IP to associate with this CloudServer. Reference the uri attribute of an arubacloud_elasticip resource. Optional — omit to use a dynamic IP. Changing this value forces a new resource.
	// URI of an Elastic IP to associate with this CloudServer. Reference the `uri` attribute of an `arubacloud_elasticip` resource. Optional — omit to use a dynamic IP. Changing this value forces a new resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Elasticip
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	ElasticIPURIRef *string `json:"elasticIpUriRef,omitempty" tf:"elastic_ip_uri_ref,omitempty"`

	// Reference to a Elasticip in arubacloud to populate elasticIpUriRef.
	// +kubebuilder:validation:Optional
	ElasticIPURIRefRef *v2.NamespacedReference `json:"elasticIpUriRefRef,omitempty" tf:"-"`

	// Selector for a Elasticip in arubacloud to populate elasticIpUriRef.
	// +kubebuilder:validation:Optional
	ElasticIPURIRefSelector *v2.NamespacedSelector `json:"elasticIpUriRefSelector,omitempty" tf:"-"`

	// (List of String) List of security group URIs to apply to this CloudServer. Reference the uri attribute of each arubacloud_securitygroup resource. Changing this value forces a new resource.
	// List of security group URIs to apply to this CloudServer. Reference the `uri` attribute of each `arubacloud_securitygroup` resource. Changing this value forces a new resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Securitygroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	SecuritygroupURIRefs []*string `json:"securitygroupUriRefs,omitempty" tf:"securitygroup_uri_refs,omitempty"`

	// References to Securitygroup in arubacloud to populate securitygroupUriRefs.
	// +kubebuilder:validation:Optional
	SecuritygroupURIRefsRefs []v2.NamespacedReference `json:"securitygroupUriRefsRefs,omitempty" tf:"-"`

	// Selector for a list of Securitygroup in arubacloud to populate securitygroupUriRefs.
	// +kubebuilder:validation:Optional
	SecuritygroupURIRefsSelector *v2.NamespacedSelector `json:"securitygroupUriRefsSelector,omitempty" tf:"-"`

	// (List of String) List of subnet URIs to attach this CloudServer to. Reference the uri attribute of each arubacloud_subnet resource. Changing this value forces a new resource.
	// List of subnet URIs to attach this CloudServer to. Reference the `uri` attribute of each `arubacloud_subnet` resource. Changing this value forces a new resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	SubnetURIRefs []*string `json:"subnetUriRefs,omitempty" tf:"subnet_uri_refs,omitempty"`

	// References to Subnet in arubacloud to populate subnetUriRefs.
	// +kubebuilder:validation:Optional
	SubnetURIRefsRefs []v2.NamespacedReference `json:"subnetUriRefsRefs,omitempty" tf:"-"`

	// Selector for a list of Subnet in arubacloud to populate subnetUriRefs.
	// +kubebuilder:validation:Optional
	SubnetURIRefsSelector *v2.NamespacedSelector `json:"subnetUriRefsSelector,omitempty" tf:"-"`

	// (String) URI of the VPC to attach this CloudServer to. Reference the uri attribute of an arubacloud_vpc resource. Changing this value forces a new resource.
	// URI of the VPC to attach this CloudServer to. Reference the `uri` attribute of an `arubacloud_vpc` resource. Changing this value forces a new resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.VPC
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`

	// Reference to a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefRef *v2.NamespacedReference `json:"vpcUriRefRef,omitempty" tf:"-"`

	// Selector for a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefSelector *v2.NamespacedSelector `json:"vpcUriRefSelector,omitempty" tf:"-"`
}

type SettingsInitParameters struct {

	// (String) Compute flavour name (e.g., CSO4A8 for 4 vCPU / 8 GB RAM). See available flavours. Changing this value forces a new resource.
	// Compute flavour name (e.g., `CSO4A8` for 4 vCPU / 8 GB RAM). See [available flavours](https://api.arubacloud.com/docs/metadata/#cloudserver-flavors). Changing this value forces a new resource.
	FlavorName *string `json:"flavorName,omitempty" tf:"flavor_name,omitempty"`

	// (String) URI of the SSH key pair to inject at boot. Reference the uri attribute of an arubacloud_keypair resource. Changing this value forces a new resource.
	// URI of the SSH key pair to inject at boot. Reference the `uri` attribute of an `arubacloud_keypair` resource. Changing this value forces a new resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Keypair
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	KeyPairURIRef *string `json:"keyPairUriRef,omitempty" tf:"key_pair_uri_ref,omitempty"`

	// Reference to a Keypair in arubacloud to populate keyPairUriRef.
	// +kubebuilder:validation:Optional
	KeyPairURIRefRef *v2.NamespacedReference `json:"keyPairUriRefRef,omitempty" tf:"-"`

	// Selector for a Keypair in arubacloud to populate keyPairUriRef.
	// +kubebuilder:validation:Optional
	KeyPairURIRefSelector *v2.NamespacedSelector `json:"keyPairUriRefSelector,omitempty" tf:"-"`

	// Init configuration passed verbatim to the instance at first boot (raw YAML or shell-script). Write-only — this value is sent to the API but is not returned in subsequent read responses. Changing this value forces a new resource.
	// Cloud-Init configuration passed verbatim to the instance at first boot (raw YAML or shell-script). Write-only — this value is sent to the API but is not returned in subsequent read responses. Changing this value forces a new resource.
	UserDataSecretRef *v2.LocalSecretKeySelector `json:"userDataSecretRef,omitempty" tf:"-"`
}

type SettingsObservation struct {

	// (String) Compute flavour name (e.g., CSO4A8 for 4 vCPU / 8 GB RAM). See available flavours. Changing this value forces a new resource.
	// Compute flavour name (e.g., `CSO4A8` for 4 vCPU / 8 GB RAM). See [available flavours](https://api.arubacloud.com/docs/metadata/#cloudserver-flavors). Changing this value forces a new resource.
	FlavorName *string `json:"flavorName,omitempty" tf:"flavor_name,omitempty"`

	// (String) URI of the SSH key pair to inject at boot. Reference the uri attribute of an arubacloud_keypair resource. Changing this value forces a new resource.
	// URI of the SSH key pair to inject at boot. Reference the `uri` attribute of an `arubacloud_keypair` resource. Changing this value forces a new resource.
	KeyPairURIRef *string `json:"keyPairUriRef,omitempty" tf:"key_pair_uri_ref,omitempty"`
}

type SettingsParameters struct {

	// (String) Compute flavour name (e.g., CSO4A8 for 4 vCPU / 8 GB RAM). See available flavours. Changing this value forces a new resource.
	// Compute flavour name (e.g., `CSO4A8` for 4 vCPU / 8 GB RAM). See [available flavours](https://api.arubacloud.com/docs/metadata/#cloudserver-flavors). Changing this value forces a new resource.
	// +kubebuilder:validation:Optional
	FlavorName *string `json:"flavorName" tf:"flavor_name,omitempty"`

	// (String) URI of the SSH key pair to inject at boot. Reference the uri attribute of an arubacloud_keypair resource. Changing this value forces a new resource.
	// URI of the SSH key pair to inject at boot. Reference the `uri` attribute of an `arubacloud_keypair` resource. Changing this value forces a new resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Keypair
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	KeyPairURIRef *string `json:"keyPairUriRef,omitempty" tf:"key_pair_uri_ref,omitempty"`

	// Reference to a Keypair in arubacloud to populate keyPairUriRef.
	// +kubebuilder:validation:Optional
	KeyPairURIRefRef *v2.NamespacedReference `json:"keyPairUriRefRef,omitempty" tf:"-"`

	// Selector for a Keypair in arubacloud to populate keyPairUriRef.
	// +kubebuilder:validation:Optional
	KeyPairURIRefSelector *v2.NamespacedSelector `json:"keyPairUriRefSelector,omitempty" tf:"-"`

	// Init configuration passed verbatim to the instance at first boot (raw YAML or shell-script). Write-only — this value is sent to the API but is not returned in subsequent read responses. Changing this value forces a new resource.
	// Cloud-Init configuration passed verbatim to the instance at first boot (raw YAML or shell-script). Write-only — this value is sent to the API but is not returned in subsequent read responses. Changing this value forces a new resource.
	// +kubebuilder:validation:Optional
	UserDataSecretRef *v2.LocalSecretKeySelector `json:"userDataSecretRef,omitempty" tf:"-"`
}

type StorageInitParameters struct {

	// (String) URI of the bootable block storage volume. Reference the uri attribute of an arubacloud_blockstorage resource (must be bootable). Changing this value forces a new resource.
	// URI of the bootable block storage volume. Reference the `uri` attribute of an `arubacloud_blockstorage` resource (must be bootable). Changing this value forces a new resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Blockstorage
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	BootVolumeURIRef *string `json:"bootVolumeUriRef,omitempty" tf:"boot_volume_uri_ref,omitempty"`

	// Reference to a Blockstorage in arubacloud to populate bootVolumeUriRef.
	// +kubebuilder:validation:Optional
	BootVolumeURIRefRef *v2.NamespacedReference `json:"bootVolumeUriRefRef,omitempty" tf:"-"`

	// Selector for a Blockstorage in arubacloud to populate bootVolumeUriRef.
	// +kubebuilder:validation:Optional
	BootVolumeURIRefSelector *v2.NamespacedSelector `json:"bootVolumeUriRefSelector,omitempty" tf:"-"`
}

type StorageObservation struct {

	// (String) URI of the bootable block storage volume. Reference the uri attribute of an arubacloud_blockstorage resource (must be bootable). Changing this value forces a new resource.
	// URI of the bootable block storage volume. Reference the `uri` attribute of an `arubacloud_blockstorage` resource (must be bootable). Changing this value forces a new resource.
	BootVolumeURIRef *string `json:"bootVolumeUriRef,omitempty" tf:"boot_volume_uri_ref,omitempty"`
}

type StorageParameters struct {

	// (String) URI of the bootable block storage volume. Reference the uri attribute of an arubacloud_blockstorage resource (must be bootable). Changing this value forces a new resource.
	// URI of the bootable block storage volume. Reference the `uri` attribute of an `arubacloud_blockstorage` resource (must be bootable). Changing this value forces a new resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Blockstorage
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	BootVolumeURIRef *string `json:"bootVolumeUriRef,omitempty" tf:"boot_volume_uri_ref,omitempty"`

	// Reference to a Blockstorage in arubacloud to populate bootVolumeUriRef.
	// +kubebuilder:validation:Optional
	BootVolumeURIRefRef *v2.NamespacedReference `json:"bootVolumeUriRefRef,omitempty" tf:"-"`

	// Selector for a Blockstorage in arubacloud to populate bootVolumeUriRef.
	// +kubebuilder:validation:Optional
	BootVolumeURIRefSelector *v2.NamespacedSelector `json:"bootVolumeUriRefSelector,omitempty" tf:"-"`
}

// CloudserverSpec defines the desired state of Cloudserver
type CloudserverSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            CloudserverParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CloudserverInitParameters `json:"initProvider,omitempty"`
}

// CloudserverStatus defines the observed state of Cloudserver.
type CloudserverStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               CloudserverObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Cloudserver is the Schema for the Cloudservers API. Manages an ArubaCloud CloudServer virtual machine.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type Cloudserver struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.network) || (has(self.initProvider) && has(self.initProvider.network))",message="spec.forProvider.network is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.settings) || (has(self.initProvider) && has(self.initProvider.settings))",message="spec.forProvider.settings is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storage) || (has(self.initProvider) && has(self.initProvider.storage))",message="spec.forProvider.storage is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   CloudserverSpec   `json:"spec"`
	Status CloudserverStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CloudserverList contains a list of Cloudservers
type CloudserverList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Cloudserver `json:"items"`
}

// Repository type metadata.
var (
	Cloudserver_Kind             = "Cloudserver"
	Cloudserver_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Cloudserver_Kind}.String()
	Cloudserver_KindAPIVersion   = Cloudserver_Kind + "." + CRDGroupVersion.String()
	Cloudserver_GroupVersionKind = CRDGroupVersion.WithKind(Cloudserver_Kind)
)

func init() {
	SchemeBuilder.Register(&Cloudserver{}, &CloudserverList{})
}
