// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DatabasebackupInitParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) Name of the logical database within the DBaaS cluster to back up.
	// Name of the logical database within the DBaaS cluster to back up.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Database
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// Reference to a Database in arubacloud to populate database.
	// +kubebuilder:validation:Optional
	DatabaseRef *v2.NamespacedReference `json:"databaseRef,omitempty" tf:"-"`

	// Selector for a Database in arubacloud to populate database.
	// +kubebuilder:validation:Optional
	DatabaseSelector *v2.NamespacedSelector `json:"databaseSelector,omitempty" tf:"-"`

	// (String) ID of the DBaaS cluster or database to back up.
	// ID of the DBaaS cluster or database to back up.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Dbaas
	DbaasID *string `json:"dbaasId,omitempty" tf:"dbaas_id,omitempty"`

	// Reference to a Dbaas in arubacloud to populate dbaasId.
	// +kubebuilder:validation:Optional
	DbaasIDRef *v2.NamespacedReference `json:"dbaasIdRef,omitempty" tf:"-"`

	// Selector for a Dbaas in arubacloud to populate dbaasId.
	// +kubebuilder:validation:Optional
	DbaasIDSelector *v2.NamespacedSelector `json:"dbaasIdSelector,omitempty" tf:"-"`

	// Bergamo). See the available locations and zones.
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Availability zone within the region where the backup is stored.
	// Availability zone within the region where the backup is stored.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DatabasebackupObservation struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) Name of the logical database within the DBaaS cluster to back up.
	// Name of the logical database within the DBaaS cluster to back up.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) ID of the DBaaS cluster or database to back up.
	// ID of the DBaaS cluster or database to back up.
	DbaasID *string `json:"dbaasId,omitempty" tf:"dbaas_id,omitempty"`

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bergamo). See the available locations and zones.
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// generated backup name assigned by the API (e.g. mysql_wordpress_20260713140736). The value provided in config is not used — the API always generates its own name.
	// Auto-generated backup name assigned by the API (e.g. `mysql_wordpress_20260713140736`). The value provided in config is not used — the API always generates its own name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources.
	// Computed by the API. Full resource URI used as a reference value in other resources.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// (String) Availability zone within the region where the backup is stored.
	// Availability zone within the region where the backup is stored.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DatabasebackupParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	// +kubebuilder:validation:Optional
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) Name of the logical database within the DBaaS cluster to back up.
	// Name of the logical database within the DBaaS cluster to back up.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Database
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// Reference to a Database in arubacloud to populate database.
	// +kubebuilder:validation:Optional
	DatabaseRef *v2.NamespacedReference `json:"databaseRef,omitempty" tf:"-"`

	// Selector for a Database in arubacloud to populate database.
	// +kubebuilder:validation:Optional
	DatabaseSelector *v2.NamespacedSelector `json:"databaseSelector,omitempty" tf:"-"`

	// (String) ID of the DBaaS cluster or database to back up.
	// ID of the DBaaS cluster or database to back up.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Dbaas
	// +kubebuilder:validation:Optional
	DbaasID *string `json:"dbaasId,omitempty" tf:"dbaas_id,omitempty"`

	// Reference to a Dbaas in arubacloud to populate dbaasId.
	// +kubebuilder:validation:Optional
	DbaasIDRef *v2.NamespacedReference `json:"dbaasIdRef,omitempty" tf:"-"`

	// Selector for a Dbaas in arubacloud to populate dbaasId.
	// +kubebuilder:validation:Optional
	DbaasIDSelector *v2.NamespacedSelector `json:"dbaasIdSelector,omitempty" tf:"-"`

	// Bergamo). See the available locations and zones.
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Availability zone within the region where the backup is stored.
	// Availability zone within the region where the backup is stored.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// DatabasebackupSpec defines the desired state of Databasebackup
type DatabasebackupSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DatabasebackupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DatabasebackupInitParameters `json:"initProvider,omitempty"`
}

// DatabasebackupStatus defines the observed state of Databasebackup.
type DatabasebackupStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DatabasebackupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Databasebackup is the Schema for the Databasebackups API. Manages a backup of an ArubaCloud DBaaS database.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type Databasebackup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.billingPeriod) || (has(self.initProvider) && has(self.initProvider.billingPeriod))",message="spec.forProvider.billingPeriod is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   DatabasebackupSpec   `json:"spec"`
	Status DatabasebackupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DatabasebackupList contains a list of Databasebackups
type DatabasebackupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Databasebackup `json:"items"`
}

// Repository type metadata.
var (
	Databasebackup_Kind             = "Databasebackup"
	Databasebackup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Databasebackup_Kind}.String()
	Databasebackup_KindAPIVersion   = Databasebackup_Kind + "." + CRDGroupVersion.String()
	Databasebackup_GroupVersionKind = CRDGroupVersion.WithKind(Databasebackup_Kind)
)

func init() {
	SchemeBuilder.Register(&Databasebackup{}, &DatabasebackupList{})
}
