// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DatabasegrantInitParameters struct {

	// created.)
	// ID of the database this grant applies to. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Database
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// Reference to a Database in arubacloud to populate database.
	// +kubebuilder:validation:Optional
	DatabaseRef *v2.NamespacedReference `json:"databaseRef,omitempty" tf:"-"`

	// Selector for a Database in arubacloud to populate database.
	// +kubebuilder:validation:Optional
	DatabaseSelector *v2.NamespacedSelector `json:"databaseSelector,omitempty" tf:"-"`

	// created.)
	// ID of the parent DBaaS cluster this grant belongs to. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Dbaas
	DbaasID *string `json:"dbaasId,omitempty" tf:"dbaas_id,omitempty"`

	// Reference to a Dbaas in arubacloud to populate dbaasId.
	// +kubebuilder:validation:Optional
	DbaasIDRef *v2.NamespacedReference `json:"dbaasIdRef,omitempty" tf:"-"`

	// Selector for a Dbaas in arubacloud to populate dbaasId.
	// +kubebuilder:validation:Optional
	DbaasIDSelector *v2.NamespacedSelector `json:"dbaasIdSelector,omitempty" tf:"-"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// place role changes. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Privilege level granted. Accepted values depend on the database engine (e.g., `ALL`, `READ`, `WRITE`). The DBaaS grant API does not support in-place role changes. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// created.)
	// Name or ID of the DBaaS user receiving the grant. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Dbaasuser
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a Dbaasuser in arubacloud to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v2.NamespacedReference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a Dbaasuser in arubacloud to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v2.NamespacedSelector `json:"userIdSelector,omitempty" tf:"-"`
}

type DatabasegrantObservation struct {

	// created.)
	// ID of the database this grant applies to. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// created.)
	// ID of the parent DBaaS cluster this grant belongs to. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	DbaasID *string `json:"dbaasId,omitempty" tf:"dbaas_id,omitempty"`

	// (String) Computed by the API. Unique identifier for the resource (composite key: project_id/dbaas_id/database/user_id).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// place role changes. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Privilege level granted. Accepted values depend on the database engine (e.g., `ALL`, `READ`, `WRITE`). The DBaaS grant API does not support in-place role changes. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources.
	// Computed by the API. Full resource URI used as a reference value in other resources.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// created.)
	// Name or ID of the DBaaS user receiving the grant. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type DatabasegrantParameters struct {

	// created.)
	// ID of the database this grant applies to. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Database
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// Reference to a Database in arubacloud to populate database.
	// +kubebuilder:validation:Optional
	DatabaseRef *v2.NamespacedReference `json:"databaseRef,omitempty" tf:"-"`

	// Selector for a Database in arubacloud to populate database.
	// +kubebuilder:validation:Optional
	DatabaseSelector *v2.NamespacedSelector `json:"databaseSelector,omitempty" tf:"-"`

	// created.)
	// ID of the parent DBaaS cluster this grant belongs to. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Dbaas
	// +kubebuilder:validation:Optional
	DbaasID *string `json:"dbaasId,omitempty" tf:"dbaas_id,omitempty"`

	// Reference to a Dbaas in arubacloud to populate dbaasId.
	// +kubebuilder:validation:Optional
	DbaasIDRef *v2.NamespacedReference `json:"dbaasIdRef,omitempty" tf:"-"`

	// Selector for a Dbaas in arubacloud to populate dbaasId.
	// +kubebuilder:validation:Optional
	DbaasIDSelector *v2.NamespacedSelector `json:"dbaasIdSelector,omitempty" tf:"-"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// place role changes. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Privilege level granted. Accepted values depend on the database engine (e.g., `ALL`, `READ`, `WRITE`). The DBaaS grant API does not support in-place role changes. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// created.)
	// Name or ID of the DBaaS user receiving the grant. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Dbaasuser
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a Dbaasuser in arubacloud to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v2.NamespacedReference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a Dbaasuser in arubacloud to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v2.NamespacedSelector `json:"userIdSelector,omitempty" tf:"-"`
}

// DatabasegrantSpec defines the desired state of Databasegrant
type DatabasegrantSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DatabasegrantParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DatabasegrantInitParameters `json:"initProvider,omitempty"`
}

// DatabasegrantStatus defines the observed state of Databasegrant.
type DatabasegrantStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DatabasegrantObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Databasegrant is the Schema for the Databasegrants API. Manages a privilege grant for an ArubaCloud DBaaS user on a specific database.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type Databasegrant struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.role) || (has(self.initProvider) && has(self.initProvider.role))",message="spec.forProvider.role is a required parameter"
	Spec   DatabasegrantSpec   `json:"spec"`
	Status DatabasegrantStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DatabasegrantList contains a list of Databasegrants
type DatabasegrantList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Databasegrant `json:"items"`
}

// Repository type metadata.
var (
	Databasegrant_Kind             = "Databasegrant"
	Databasegrant_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Databasegrant_Kind}.String()
	Databasegrant_KindAPIVersion   = Databasegrant_Kind + "." + CRDGroupVersion.String()
	Databasegrant_GroupVersionKind = CRDGroupVersion.WithKind(Databasegrant_Kind)
)

func init() {
	SchemeBuilder.Register(&Databasegrant{}, &DatabasegrantList{})
}
