// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AutoscalingInitParameters struct {

	// (Number) Minimum available space threshold in GB. When the available storage falls below this value, autoscaling increases storage by the step_size amount.
	// Minimum available space threshold in GB. When the available storage falls below this value, autoscaling increases storage by the `step_size` amount.
	AvailableSpace *float64 `json:"availableSpace,omitempty" tf:"available_space,omitempty"`

	// (Boolean) Whether storage autoscaling is enabled.
	// Whether storage autoscaling is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Amount of storage (in GB) added on each autoscaling event.
	// Amount of storage (in GB) added on each autoscaling event.
	StepSize *float64 `json:"stepSize,omitempty" tf:"step_size,omitempty"`
}

type AutoscalingObservation struct {

	// (Number) Minimum available space threshold in GB. When the available storage falls below this value, autoscaling increases storage by the step_size amount.
	// Minimum available space threshold in GB. When the available storage falls below this value, autoscaling increases storage by the `step_size` amount.
	AvailableSpace *float64 `json:"availableSpace,omitempty" tf:"available_space,omitempty"`

	// (Boolean) Whether storage autoscaling is enabled.
	// Whether storage autoscaling is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Amount of storage (in GB) added on each autoscaling event.
	// Amount of storage (in GB) added on each autoscaling event.
	StepSize *float64 `json:"stepSize,omitempty" tf:"step_size,omitempty"`
}

type AutoscalingParameters struct {

	// (Number) Minimum available space threshold in GB. When the available storage falls below this value, autoscaling increases storage by the step_size amount.
	// Minimum available space threshold in GB. When the available storage falls below this value, autoscaling increases storage by the `step_size` amount.
	// +kubebuilder:validation:Optional
	AvailableSpace *float64 `json:"availableSpace" tf:"available_space,omitempty"`

	// (Boolean) Whether storage autoscaling is enabled.
	// Whether storage autoscaling is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// (Number) Amount of storage (in GB) added on each autoscaling event.
	// Amount of storage (in GB) added on each autoscaling event.
	// +kubebuilder:validation:Optional
	StepSize *float64 `json:"stepSize" tf:"step_size,omitempty"`
}

type DbaasInitParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year. If omitted, the value returned by the API is used (Computed).
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`. If omitted, the value returned by the API is used (Computed).
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// 8.0 for MySQL 8.0, postgresql-15 for PostgreSQL 15). See the available engines. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Database engine type and version identifier (e.g., `mysql-8.0` for MySQL 8.0, `postgresql-15` for PostgreSQL 15). See the [available engines](https://api.arubacloud.com/docs/metadata/#dbaas-engines). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	EngineID *string `json:"engineId,omitempty" tf:"engine_id,omitempty"`

	// (String) Compute flavour for the DBaaS cluster nodes. See available flavours. For example, DBO2A4 means 2 vCPU and 4 GB RAM.
	// Compute flavour for the DBaaS cluster nodes. See [available flavours](https://api.arubacloud.com/docs/metadata/#dbaas-flavors). For example, `DBO2A4` means 2 vCPU and 4 GB RAM.
	Flavor *string `json:"flavor,omitempty" tf:"flavor,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the DBaaS cluster.
	// Display name for the DBaaS cluster.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the DBaaS instance. All URI references are immutable after creation. (see below for nested schema)
	Network *DbaasNetworkInitParameters `json:"network,omitempty" tf:"network,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Attributes) Storage configuration for the DBaaS instance. (see below for nested schema)
	Storage *DbaasStorageInitParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// created.)
	// Availability zone within the region where the DBaaS cluster is deployed. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DbaasNetworkInitParameters struct {

	// (String) Optional URI reference to an Elastic IP resource.
	// Optional URI reference to an Elastic IP resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Elasticip
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	ElasticIPURIRef *string `json:"elasticIpUriRef,omitempty" tf:"elastic_ip_uri_ref,omitempty"`

	// Reference to a Elasticip in arubacloud to populate elasticIpUriRef.
	// +kubebuilder:validation:Optional
	ElasticIPURIRefRef *v2.NamespacedReference `json:"elasticIpUriRefRef,omitempty" tf:"-"`

	// Selector for a Elasticip in arubacloud to populate elasticIpUriRef.
	// +kubebuilder:validation:Optional
	ElasticIPURIRefSelector *v2.NamespacedSelector `json:"elasticIpUriRefSelector,omitempty" tf:"-"`

	// (String) URI reference to the Security Group resource.
	// URI reference to the Security Group resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Securitygroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	SecurityGroupURIRef *string `json:"securityGroupUriRef,omitempty" tf:"security_group_uri_ref,omitempty"`

	// Reference to a Securitygroup in arubacloud to populate securityGroupUriRef.
	// +kubebuilder:validation:Optional
	SecurityGroupURIRefRef *v2.NamespacedReference `json:"securityGroupUriRefRef,omitempty" tf:"-"`

	// Selector for a Securitygroup in arubacloud to populate securityGroupUriRef.
	// +kubebuilder:validation:Optional
	SecurityGroupURIRefSelector *v2.NamespacedSelector `json:"securityGroupUriRefSelector,omitempty" tf:"-"`

	// (String) URI reference to the Subnet resource.
	// URI reference to the Subnet resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	SubnetURIRef *string `json:"subnetUriRef,omitempty" tf:"subnet_uri_ref,omitempty"`

	// Reference to a Subnet in arubacloud to populate subnetUriRef.
	// +kubebuilder:validation:Optional
	SubnetURIRefRef *v2.NamespacedReference `json:"subnetUriRefRef,omitempty" tf:"-"`

	// Selector for a Subnet in arubacloud to populate subnetUriRef.
	// +kubebuilder:validation:Optional
	SubnetURIRefSelector *v2.NamespacedSelector `json:"subnetUriRefSelector,omitempty" tf:"-"`

	// (String) URI reference to the VPC resource.
	// URI reference to the VPC resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.VPC
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`

	// Reference to a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefRef *v2.NamespacedReference `json:"vpcUriRefRef,omitempty" tf:"-"`

	// Selector for a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefSelector *v2.NamespacedSelector `json:"vpcUriRefSelector,omitempty" tf:"-"`
}

type DbaasNetworkObservation struct {

	// (String) Optional URI reference to an Elastic IP resource.
	// Optional URI reference to an Elastic IP resource.
	ElasticIPURIRef *string `json:"elasticIpUriRef,omitempty" tf:"elastic_ip_uri_ref,omitempty"`

	// (String) URI reference to the Security Group resource.
	// URI reference to the Security Group resource.
	SecurityGroupURIRef *string `json:"securityGroupUriRef,omitempty" tf:"security_group_uri_ref,omitempty"`

	// (String) URI reference to the Subnet resource.
	// URI reference to the Subnet resource.
	SubnetURIRef *string `json:"subnetUriRef,omitempty" tf:"subnet_uri_ref,omitempty"`

	// (String) URI reference to the VPC resource.
	// URI reference to the VPC resource.
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`
}

type DbaasNetworkParameters struct {

	// (String) Optional URI reference to an Elastic IP resource.
	// Optional URI reference to an Elastic IP resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Elasticip
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	ElasticIPURIRef *string `json:"elasticIpUriRef,omitempty" tf:"elastic_ip_uri_ref,omitempty"`

	// Reference to a Elasticip in arubacloud to populate elasticIpUriRef.
	// +kubebuilder:validation:Optional
	ElasticIPURIRefRef *v2.NamespacedReference `json:"elasticIpUriRefRef,omitempty" tf:"-"`

	// Selector for a Elasticip in arubacloud to populate elasticIpUriRef.
	// +kubebuilder:validation:Optional
	ElasticIPURIRefSelector *v2.NamespacedSelector `json:"elasticIpUriRefSelector,omitempty" tf:"-"`

	// (String) URI reference to the Security Group resource.
	// URI reference to the Security Group resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Securitygroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	SecurityGroupURIRef *string `json:"securityGroupUriRef,omitempty" tf:"security_group_uri_ref,omitempty"`

	// Reference to a Securitygroup in arubacloud to populate securityGroupUriRef.
	// +kubebuilder:validation:Optional
	SecurityGroupURIRefRef *v2.NamespacedReference `json:"securityGroupUriRefRef,omitempty" tf:"-"`

	// Selector for a Securitygroup in arubacloud to populate securityGroupUriRef.
	// +kubebuilder:validation:Optional
	SecurityGroupURIRefSelector *v2.NamespacedSelector `json:"securityGroupUriRefSelector,omitempty" tf:"-"`

	// (String) URI reference to the Subnet resource.
	// URI reference to the Subnet resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	SubnetURIRef *string `json:"subnetUriRef,omitempty" tf:"subnet_uri_ref,omitempty"`

	// Reference to a Subnet in arubacloud to populate subnetUriRef.
	// +kubebuilder:validation:Optional
	SubnetURIRefRef *v2.NamespacedReference `json:"subnetUriRefRef,omitempty" tf:"-"`

	// Selector for a Subnet in arubacloud to populate subnetUriRef.
	// +kubebuilder:validation:Optional
	SubnetURIRefSelector *v2.NamespacedSelector `json:"subnetUriRefSelector,omitempty" tf:"-"`

	// (String) URI reference to the VPC resource.
	// URI reference to the VPC resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.VPC
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`

	// Reference to a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefRef *v2.NamespacedReference `json:"vpcUriRefRef,omitempty" tf:"-"`

	// Selector for a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefSelector *v2.NamespacedSelector `json:"vpcUriRefSelector,omitempty" tf:"-"`
}

type DbaasObservation struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year. If omitted, the value returned by the API is used (Computed).
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`. If omitted, the value returned by the API is used (Computed).
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// 8.0 for MySQL 8.0, postgresql-15 for PostgreSQL 15). See the available engines. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Database engine type and version identifier (e.g., `mysql-8.0` for MySQL 8.0, `postgresql-15` for PostgreSQL 15). See the [available engines](https://api.arubacloud.com/docs/metadata/#dbaas-engines). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	EngineID *string `json:"engineId,omitempty" tf:"engine_id,omitempty"`

	// (String) Compute flavour for the DBaaS cluster nodes. See available flavours. For example, DBO2A4 means 2 vCPU and 4 GB RAM.
	// Compute flavour for the DBaaS cluster nodes. See [available flavours](https://api.arubacloud.com/docs/metadata/#dbaas-flavors). For example, `DBO2A4` means 2 vCPU and 4 GB RAM.
	Flavor *string `json:"flavor,omitempty" tf:"flavor,omitempty"`

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the DBaaS cluster.
	// Display name for the DBaaS cluster.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the DBaaS instance. All URI references are immutable after creation. (see below for nested schema)
	Network *DbaasNetworkObservation `json:"network,omitempty" tf:"network,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Storage configuration for the DBaaS instance. (see below for nested schema)
	Storage *DbaasStorageObservation `json:"storage,omitempty" tf:"storage,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources.
	// Computed by the API. Full resource URI used as a reference value in other resources.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// created.)
	// Availability zone within the region where the DBaaS cluster is deployed. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DbaasParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year. If omitted, the value returned by the API is used (Computed).
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`. If omitted, the value returned by the API is used (Computed).
	// +kubebuilder:validation:Optional
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// 8.0 for MySQL 8.0, postgresql-15 for PostgreSQL 15). See the available engines. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Database engine type and version identifier (e.g., `mysql-8.0` for MySQL 8.0, `postgresql-15` for PostgreSQL 15). See the [available engines](https://api.arubacloud.com/docs/metadata/#dbaas-engines). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Optional
	EngineID *string `json:"engineId,omitempty" tf:"engine_id,omitempty"`

	// (String) Compute flavour for the DBaaS cluster nodes. See available flavours. For example, DBO2A4 means 2 vCPU and 4 GB RAM.
	// Compute flavour for the DBaaS cluster nodes. See [available flavours](https://api.arubacloud.com/docs/metadata/#dbaas-flavors). For example, `DBO2A4` means 2 vCPU and 4 GB RAM.
	// +kubebuilder:validation:Optional
	Flavor *string `json:"flavor,omitempty" tf:"flavor,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the DBaaS cluster.
	// Display name for the DBaaS cluster.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the DBaaS instance. All URI references are immutable after creation. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Network *DbaasNetworkParameters `json:"network,omitempty" tf:"network,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Attributes) Storage configuration for the DBaaS instance. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Storage *DbaasStorageParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// created.)
	// Availability zone within the region where the DBaaS cluster is deployed. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DbaasStorageInitParameters struct {

	// (Attributes) Optional autoscaling configuration for the DBaaS storage. (see below for nested schema)
	Autoscaling *AutoscalingInitParameters `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (Number) Storage size in GB for the DBaaS instance.
	// Storage size in GB for the DBaaS instance.
	SizeGb *float64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`
}

type DbaasStorageObservation struct {

	// (Attributes) Optional autoscaling configuration for the DBaaS storage. (see below for nested schema)
	Autoscaling *AutoscalingObservation `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (Number) Storage size in GB for the DBaaS instance.
	// Storage size in GB for the DBaaS instance.
	SizeGb *float64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`
}

type DbaasStorageParameters struct {

	// (Attributes) Optional autoscaling configuration for the DBaaS storage. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Autoscaling *AutoscalingParameters `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (Number) Storage size in GB for the DBaaS instance.
	// Storage size in GB for the DBaaS instance.
	// +kubebuilder:validation:Optional
	SizeGb *float64 `json:"sizeGb" tf:"size_gb,omitempty"`
}

// DbaasSpec defines the desired state of Dbaas
type DbaasSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DbaasParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DbaasInitParameters `json:"initProvider,omitempty"`
}

// DbaasStatus defines the observed state of Dbaas.
type DbaasStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DbaasObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Dbaas is the Schema for the Dbaass API. Manages an ArubaCloud DBaaS cluster — a managed database cluster with automated backups and high availability.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type Dbaas struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.engineId) || (has(self.initProvider) && has(self.initProvider.engineId))",message="spec.forProvider.engineId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.flavor) || (has(self.initProvider) && has(self.initProvider.flavor))",message="spec.forProvider.flavor is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.network) || (has(self.initProvider) && has(self.initProvider.network))",message="spec.forProvider.network is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storage) || (has(self.initProvider) && has(self.initProvider.storage))",message="spec.forProvider.storage is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   DbaasSpec   `json:"spec"`
	Status DbaasStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DbaasList contains a list of Dbaass
type DbaasList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Dbaas `json:"items"`
}

// Repository type metadata.
var (
	Dbaas_Kind             = "Dbaas"
	Dbaas_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Dbaas_Kind}.String()
	Dbaas_KindAPIVersion   = Dbaas_Kind + "." + CRDGroupVersion.String()
	Dbaas_GroupVersionKind = CRDGroupVersion.WithKind(Dbaas_Kind)
)

func init() {
	SchemeBuilder.Register(&Dbaas{}, &DbaasList{})
}
