// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Backup.
func (mg *Backup) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VolumeID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VolumeIDRef,
		Selector:     mg.Spec.ForProvider.VolumeIDSelector,
		To: reference.To{
			List:    &BlockstorageList{},
			Managed: &Blockstorage{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VolumeID")
	}
	mg.Spec.ForProvider.VolumeID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VolumeIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VolumeID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VolumeIDRef,
		Selector:     mg.Spec.InitProvider.VolumeIDSelector,
		To: reference.To{
			List:    &BlockstorageList{},
			Managed: &Blockstorage{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VolumeID")
	}
	mg.Spec.InitProvider.VolumeID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VolumeIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Blockstorage.
func (mg *Blockstorage) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Cloudserver.
func (mg *Cloudserver) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Network.ElasticIPURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Network.ElasticIPURIRefRef,
			Selector:     mg.Spec.ForProvider.Network.ElasticIPURIRefSelector,
			To: reference.To{
				List:    &ElasticipList{},
				Managed: &Elasticip{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.ElasticIPURIRef")
		}
		mg.Spec.ForProvider.Network.ElasticIPURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Network.ElasticIPURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.Network != nil {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.Network.SecuritygroupURIRefs),
			Extract:       resource.ExtractParamPath("uri", true),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.ForProvider.Network.SecuritygroupURIRefsRefs,
			Selector:      mg.Spec.ForProvider.Network.SecuritygroupURIRefsSelector,
			To: reference.To{
				List:    &SecuritygroupList{},
				Managed: &Securitygroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.SecuritygroupURIRefs")
		}
		mg.Spec.ForProvider.Network.SecuritygroupURIRefs = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.ForProvider.Network.SecuritygroupURIRefsRefs = mrsp.ResolvedReferences

	}
	if mg.Spec.ForProvider.Network != nil {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.Network.SubnetURIRefs),
			Extract:       resource.ExtractParamPath("uri", true),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.ForProvider.Network.SubnetURIRefsRefs,
			Selector:      mg.Spec.ForProvider.Network.SubnetURIRefsSelector,
			To: reference.To{
				List:    &SubnetList{},
				Managed: &Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.SubnetURIRefs")
		}
		mg.Spec.ForProvider.Network.SubnetURIRefs = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.ForProvider.Network.SubnetURIRefsRefs = mrsp.ResolvedReferences

	}
	if mg.Spec.ForProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Network.VPCURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Network.VPCURIRefRef,
			Selector:     mg.Spec.ForProvider.Network.VPCURIRefSelector,
			To: reference.To{
				List:    &VPCList{},
				Managed: &VPC{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.VPCURIRef")
		}
		mg.Spec.ForProvider.Network.VPCURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Network.VPCURIRefRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	if mg.Spec.ForProvider.Settings != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Settings.KeyPairURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Settings.KeyPairURIRefRef,
			Selector:     mg.Spec.ForProvider.Settings.KeyPairURIRefSelector,
			To: reference.To{
				List:    &KeypairList{},
				Managed: &Keypair{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Settings.KeyPairURIRef")
		}
		mg.Spec.ForProvider.Settings.KeyPairURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Settings.KeyPairURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.Storage != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Storage.BootVolumeURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Storage.BootVolumeURIRefRef,
			Selector:     mg.Spec.ForProvider.Storage.BootVolumeURIRefSelector,
			To: reference.To{
				List:    &BlockstorageList{},
				Managed: &Blockstorage{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Storage.BootVolumeURIRef")
		}
		mg.Spec.ForProvider.Storage.BootVolumeURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Storage.BootVolumeURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Network.ElasticIPURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Network.ElasticIPURIRefRef,
			Selector:     mg.Spec.InitProvider.Network.ElasticIPURIRefSelector,
			To: reference.To{
				List:    &ElasticipList{},
				Managed: &Elasticip{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.ElasticIPURIRef")
		}
		mg.Spec.InitProvider.Network.ElasticIPURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Network.ElasticIPURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Network != nil {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.Network.SecuritygroupURIRefs),
			Extract:       resource.ExtractParamPath("uri", true),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.InitProvider.Network.SecuritygroupURIRefsRefs,
			Selector:      mg.Spec.InitProvider.Network.SecuritygroupURIRefsSelector,
			To: reference.To{
				List:    &SecuritygroupList{},
				Managed: &Securitygroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.SecuritygroupURIRefs")
		}
		mg.Spec.InitProvider.Network.SecuritygroupURIRefs = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.InitProvider.Network.SecuritygroupURIRefsRefs = mrsp.ResolvedReferences

	}
	if mg.Spec.InitProvider.Network != nil {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.Network.SubnetURIRefs),
			Extract:       resource.ExtractParamPath("uri", true),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.InitProvider.Network.SubnetURIRefsRefs,
			Selector:      mg.Spec.InitProvider.Network.SubnetURIRefsSelector,
			To: reference.To{
				List:    &SubnetList{},
				Managed: &Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.SubnetURIRefs")
		}
		mg.Spec.InitProvider.Network.SubnetURIRefs = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.InitProvider.Network.SubnetURIRefsRefs = mrsp.ResolvedReferences

	}
	if mg.Spec.InitProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Network.VPCURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Network.VPCURIRefRef,
			Selector:     mg.Spec.InitProvider.Network.VPCURIRefSelector,
			To: reference.To{
				List:    &VPCList{},
				Managed: &VPC{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.VPCURIRef")
		}
		mg.Spec.InitProvider.Network.VPCURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Network.VPCURIRefRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	if mg.Spec.InitProvider.Settings != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Settings.KeyPairURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Settings.KeyPairURIRefRef,
			Selector:     mg.Spec.InitProvider.Settings.KeyPairURIRefSelector,
			To: reference.To{
				List:    &KeypairList{},
				Managed: &Keypair{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Settings.KeyPairURIRef")
		}
		mg.Spec.InitProvider.Settings.KeyPairURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Settings.KeyPairURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Storage != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Storage.BootVolumeURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Storage.BootVolumeURIRefRef,
			Selector:     mg.Spec.InitProvider.Storage.BootVolumeURIRefSelector,
			To: reference.To{
				List:    &BlockstorageList{},
				Managed: &Blockstorage{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Storage.BootVolumeURIRef")
		}
		mg.Spec.InitProvider.Storage.BootVolumeURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Storage.BootVolumeURIRefRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this Containerregistry.
func (mg *Containerregistry) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Network.PublicIPURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Network.PublicIPURIRefRef,
			Selector:     mg.Spec.ForProvider.Network.PublicIPURIRefSelector,
			To: reference.To{
				List:    &ElasticipList{},
				Managed: &Elasticip{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.PublicIPURIRef")
		}
		mg.Spec.ForProvider.Network.PublicIPURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Network.PublicIPURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Network.SecurityGroupURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Network.SecurityGroupURIRefRef,
			Selector:     mg.Spec.ForProvider.Network.SecurityGroupURIRefSelector,
			To: reference.To{
				List:    &SecuritygroupList{},
				Managed: &Securitygroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.SecurityGroupURIRef")
		}
		mg.Spec.ForProvider.Network.SecurityGroupURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Network.SecurityGroupURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Network.SubnetURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Network.SubnetURIRefRef,
			Selector:     mg.Spec.ForProvider.Network.SubnetURIRefSelector,
			To: reference.To{
				List:    &SubnetList{},
				Managed: &Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.SubnetURIRef")
		}
		mg.Spec.ForProvider.Network.SubnetURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Network.SubnetURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Network.VPCURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Network.VPCURIRefRef,
			Selector:     mg.Spec.ForProvider.Network.VPCURIRefSelector,
			To: reference.To{
				List:    &VPCList{},
				Managed: &VPC{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.VPCURIRef")
		}
		mg.Spec.ForProvider.Network.VPCURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Network.VPCURIRefRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	if mg.Spec.ForProvider.Storage != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Storage.BlockStorageURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Storage.BlockStorageURIRefRef,
			Selector:     mg.Spec.ForProvider.Storage.BlockStorageURIRefSelector,
			To: reference.To{
				List:    &BlockstorageList{},
				Managed: &Blockstorage{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Storage.BlockStorageURIRef")
		}
		mg.Spec.ForProvider.Storage.BlockStorageURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Storage.BlockStorageURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Network.PublicIPURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Network.PublicIPURIRefRef,
			Selector:     mg.Spec.InitProvider.Network.PublicIPURIRefSelector,
			To: reference.To{
				List:    &ElasticipList{},
				Managed: &Elasticip{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.PublicIPURIRef")
		}
		mg.Spec.InitProvider.Network.PublicIPURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Network.PublicIPURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Network.SecurityGroupURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Network.SecurityGroupURIRefRef,
			Selector:     mg.Spec.InitProvider.Network.SecurityGroupURIRefSelector,
			To: reference.To{
				List:    &SecuritygroupList{},
				Managed: &Securitygroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.SecurityGroupURIRef")
		}
		mg.Spec.InitProvider.Network.SecurityGroupURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Network.SecurityGroupURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Network.SubnetURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Network.SubnetURIRefRef,
			Selector:     mg.Spec.InitProvider.Network.SubnetURIRefSelector,
			To: reference.To{
				List:    &SubnetList{},
				Managed: &Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.SubnetURIRef")
		}
		mg.Spec.InitProvider.Network.SubnetURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Network.SubnetURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Network.VPCURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Network.VPCURIRefRef,
			Selector:     mg.Spec.InitProvider.Network.VPCURIRefSelector,
			To: reference.To{
				List:    &VPCList{},
				Managed: &VPC{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.VPCURIRef")
		}
		mg.Spec.InitProvider.Network.VPCURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Network.VPCURIRefRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	if mg.Spec.InitProvider.Storage != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Storage.BlockStorageURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Storage.BlockStorageURIRefRef,
			Selector:     mg.Spec.InitProvider.Storage.BlockStorageURIRefSelector,
			To: reference.To{
				List:    &BlockstorageList{},
				Managed: &Blockstorage{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Storage.BlockStorageURIRef")
		}
		mg.Spec.InitProvider.Storage.BlockStorageURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Storage.BlockStorageURIRefRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this Database.
func (mg *Database) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DbaasID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DbaasIDRef,
		Selector:     mg.Spec.ForProvider.DbaasIDSelector,
		To: reference.To{
			List:    &DbaasList{},
			Managed: &Dbaas{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DbaasID")
	}
	mg.Spec.ForProvider.DbaasID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DbaasIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DbaasID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DbaasIDRef,
		Selector:     mg.Spec.InitProvider.DbaasIDSelector,
		To: reference.To{
			List:    &DbaasList{},
			Managed: &Dbaas{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DbaasID")
	}
	mg.Spec.InitProvider.DbaasID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DbaasIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Databasebackup.
func (mg *Databasebackup) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Database),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DatabaseRef,
		Selector:     mg.Spec.ForProvider.DatabaseSelector,
		To: reference.To{
			List:    &DatabaseList{},
			Managed: &Database{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Database")
	}
	mg.Spec.ForProvider.Database = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DatabaseRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DbaasID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DbaasIDRef,
		Selector:     mg.Spec.ForProvider.DbaasIDSelector,
		To: reference.To{
			List:    &DbaasList{},
			Managed: &Dbaas{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DbaasID")
	}
	mg.Spec.ForProvider.DbaasID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DbaasIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Database),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DatabaseRef,
		Selector:     mg.Spec.InitProvider.DatabaseSelector,
		To: reference.To{
			List:    &DatabaseList{},
			Managed: &Database{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Database")
	}
	mg.Spec.InitProvider.Database = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DatabaseRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DbaasID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DbaasIDRef,
		Selector:     mg.Spec.InitProvider.DbaasIDSelector,
		To: reference.To{
			List:    &DbaasList{},
			Managed: &Dbaas{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DbaasID")
	}
	mg.Spec.InitProvider.DbaasID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DbaasIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Databasegrant.
func (mg *Databasegrant) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Database),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DatabaseRef,
		Selector:     mg.Spec.ForProvider.DatabaseSelector,
		To: reference.To{
			List:    &DatabaseList{},
			Managed: &Database{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Database")
	}
	mg.Spec.ForProvider.Database = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DatabaseRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DbaasID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DbaasIDRef,
		Selector:     mg.Spec.ForProvider.DbaasIDSelector,
		To: reference.To{
			List:    &DbaasList{},
			Managed: &Dbaas{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DbaasID")
	}
	mg.Spec.ForProvider.DbaasID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DbaasIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.UserID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.UserIDRef,
		Selector:     mg.Spec.ForProvider.UserIDSelector,
		To: reference.To{
			List:    &DbaasuserList{},
			Managed: &Dbaasuser{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.UserID")
	}
	mg.Spec.ForProvider.UserID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.UserIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Database),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DatabaseRef,
		Selector:     mg.Spec.InitProvider.DatabaseSelector,
		To: reference.To{
			List:    &DatabaseList{},
			Managed: &Database{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Database")
	}
	mg.Spec.InitProvider.Database = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DatabaseRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DbaasID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DbaasIDRef,
		Selector:     mg.Spec.InitProvider.DbaasIDSelector,
		To: reference.To{
			List:    &DbaasList{},
			Managed: &Dbaas{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DbaasID")
	}
	mg.Spec.InitProvider.DbaasID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DbaasIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.UserID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.UserIDRef,
		Selector:     mg.Spec.InitProvider.UserIDSelector,
		To: reference.To{
			List:    &DbaasuserList{},
			Managed: &Dbaasuser{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.UserID")
	}
	mg.Spec.InitProvider.UserID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.UserIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Dbaas.
func (mg *Dbaas) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Network.ElasticIPURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Network.ElasticIPURIRefRef,
			Selector:     mg.Spec.ForProvider.Network.ElasticIPURIRefSelector,
			To: reference.To{
				List:    &ElasticipList{},
				Managed: &Elasticip{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.ElasticIPURIRef")
		}
		mg.Spec.ForProvider.Network.ElasticIPURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Network.ElasticIPURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Network.SecurityGroupURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Network.SecurityGroupURIRefRef,
			Selector:     mg.Spec.ForProvider.Network.SecurityGroupURIRefSelector,
			To: reference.To{
				List:    &SecuritygroupList{},
				Managed: &Securitygroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.SecurityGroupURIRef")
		}
		mg.Spec.ForProvider.Network.SecurityGroupURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Network.SecurityGroupURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Network.SubnetURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Network.SubnetURIRefRef,
			Selector:     mg.Spec.ForProvider.Network.SubnetURIRefSelector,
			To: reference.To{
				List:    &SubnetList{},
				Managed: &Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.SubnetURIRef")
		}
		mg.Spec.ForProvider.Network.SubnetURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Network.SubnetURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Network.VPCURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Network.VPCURIRefRef,
			Selector:     mg.Spec.ForProvider.Network.VPCURIRefSelector,
			To: reference.To{
				List:    &VPCList{},
				Managed: &VPC{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.VPCURIRef")
		}
		mg.Spec.ForProvider.Network.VPCURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Network.VPCURIRefRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	if mg.Spec.InitProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Network.ElasticIPURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Network.ElasticIPURIRefRef,
			Selector:     mg.Spec.InitProvider.Network.ElasticIPURIRefSelector,
			To: reference.To{
				List:    &ElasticipList{},
				Managed: &Elasticip{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.ElasticIPURIRef")
		}
		mg.Spec.InitProvider.Network.ElasticIPURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Network.ElasticIPURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Network.SecurityGroupURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Network.SecurityGroupURIRefRef,
			Selector:     mg.Spec.InitProvider.Network.SecurityGroupURIRefSelector,
			To: reference.To{
				List:    &SecuritygroupList{},
				Managed: &Securitygroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.SecurityGroupURIRef")
		}
		mg.Spec.InitProvider.Network.SecurityGroupURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Network.SecurityGroupURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Network.SubnetURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Network.SubnetURIRefRef,
			Selector:     mg.Spec.InitProvider.Network.SubnetURIRefSelector,
			To: reference.To{
				List:    &SubnetList{},
				Managed: &Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.SubnetURIRef")
		}
		mg.Spec.InitProvider.Network.SubnetURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Network.SubnetURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Network.VPCURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Network.VPCURIRefRef,
			Selector:     mg.Spec.InitProvider.Network.VPCURIRefSelector,
			To: reference.To{
				List:    &VPCList{},
				Managed: &VPC{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.VPCURIRef")
		}
		mg.Spec.InitProvider.Network.VPCURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Network.VPCURIRefRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Dbaasuser.
func (mg *Dbaasuser) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DbaasID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DbaasIDRef,
		Selector:     mg.Spec.ForProvider.DbaasIDSelector,
		To: reference.To{
			List:    &DbaasList{},
			Managed: &Dbaas{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DbaasID")
	}
	mg.Spec.ForProvider.DbaasID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DbaasIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DbaasID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DbaasIDRef,
		Selector:     mg.Spec.InitProvider.DbaasIDSelector,
		To: reference.To{
			List:    &DbaasList{},
			Managed: &Dbaas{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DbaasID")
	}
	mg.Spec.InitProvider.DbaasID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DbaasIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Elasticip.
func (mg *Elasticip) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this KMS.
func (mg *KMS) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Kaas.
func (mg *Kaas) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Network.SecurityGroupName),
			Extract:      resource.ExtractParamPath("name", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Network.SecurityGroupNameRef,
			Selector:     mg.Spec.ForProvider.Network.SecurityGroupNameSelector,
			To: reference.To{
				List:    &SecuritygroupList{},
				Managed: &Securitygroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.SecurityGroupName")
		}
		mg.Spec.ForProvider.Network.SecurityGroupName = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Network.SecurityGroupNameRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Network.SubnetURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Network.SubnetURIRefRef,
			Selector:     mg.Spec.ForProvider.Network.SubnetURIRefSelector,
			To: reference.To{
				List:    &SubnetList{},
				Managed: &Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.SubnetURIRef")
		}
		mg.Spec.ForProvider.Network.SubnetURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Network.SubnetURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Network.VPCURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Network.VPCURIRefRef,
			Selector:     mg.Spec.ForProvider.Network.VPCURIRefSelector,
			To: reference.To{
				List:    &VPCList{},
				Managed: &VPC{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.VPCURIRef")
		}
		mg.Spec.ForProvider.Network.VPCURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Network.VPCURIRefRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	if mg.Spec.InitProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Network.SecurityGroupName),
			Extract:      resource.ExtractParamPath("name", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Network.SecurityGroupNameRef,
			Selector:     mg.Spec.InitProvider.Network.SecurityGroupNameSelector,
			To: reference.To{
				List:    &SecuritygroupList{},
				Managed: &Securitygroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.SecurityGroupName")
		}
		mg.Spec.InitProvider.Network.SecurityGroupName = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Network.SecurityGroupNameRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Network.SubnetURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Network.SubnetURIRefRef,
			Selector:     mg.Spec.InitProvider.Network.SubnetURIRefSelector,
			To: reference.To{
				List:    &SubnetList{},
				Managed: &Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.SubnetURIRef")
		}
		mg.Spec.InitProvider.Network.SubnetURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Network.SubnetURIRefRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Network != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Network.VPCURIRef),
			Extract:      resource.ExtractParamPath("uri", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Network.VPCURIRefRef,
			Selector:     mg.Spec.InitProvider.Network.VPCURIRefSelector,
			To: reference.To{
				List:    &VPCList{},
				Managed: &VPC{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.VPCURIRef")
		}
		mg.Spec.InitProvider.Network.VPCURIRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Network.VPCURIRefRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Keypair.
func (mg *Keypair) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Restore.
func (mg *Restore) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BackupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BackupIDRef,
		Selector:     mg.Spec.ForProvider.BackupIDSelector,
		To: reference.To{
			List:    &BackupList{},
			Managed: &Backup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BackupID")
	}
	mg.Spec.ForProvider.BackupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BackupIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VolumeID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VolumeIDRef,
		Selector:     mg.Spec.ForProvider.VolumeIDSelector,
		To: reference.To{
			List:    &BlockstorageList{},
			Managed: &Blockstorage{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VolumeID")
	}
	mg.Spec.ForProvider.VolumeID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VolumeIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BackupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BackupIDRef,
		Selector:     mg.Spec.InitProvider.BackupIDSelector,
		To: reference.To{
			List:    &BackupList{},
			Managed: &Backup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BackupID")
	}
	mg.Spec.InitProvider.BackupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BackupIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VolumeID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VolumeIDRef,
		Selector:     mg.Spec.InitProvider.VolumeIDSelector,
		To: reference.To{
			List:    &BlockstorageList{},
			Managed: &Blockstorage{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VolumeID")
	}
	mg.Spec.InitProvider.VolumeID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VolumeIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Schedulejob.
func (mg *Schedulejob) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Securitygroup.
func (mg *Securitygroup) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VPCID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VPCIDRef,
		Selector:     mg.Spec.ForProvider.VPCIDSelector,
		To: reference.To{
			List:    &VPCList{},
			Managed: &VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VPCID")
	}
	mg.Spec.ForProvider.VPCID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VPCIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VPCID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VPCIDRef,
		Selector:     mg.Spec.InitProvider.VPCIDSelector,
		To: reference.To{
			List:    &VPCList{},
			Managed: &VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VPCID")
	}
	mg.Spec.InitProvider.VPCID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VPCIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Securityrule.
func (mg *Securityrule) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SecurityGroupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SecurityGroupIDRef,
		Selector:     mg.Spec.ForProvider.SecurityGroupIDSelector,
		To: reference.To{
			List:    &SecuritygroupList{},
			Managed: &Securitygroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SecurityGroupID")
	}
	mg.Spec.ForProvider.SecurityGroupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SecurityGroupIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VPCID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VPCIDRef,
		Selector:     mg.Spec.ForProvider.VPCIDSelector,
		To: reference.To{
			List:    &VPCList{},
			Managed: &VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VPCID")
	}
	mg.Spec.ForProvider.VPCID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VPCIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SecurityGroupID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SecurityGroupIDRef,
		Selector:     mg.Spec.InitProvider.SecurityGroupIDSelector,
		To: reference.To{
			List:    &SecuritygroupList{},
			Managed: &Securitygroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SecurityGroupID")
	}
	mg.Spec.InitProvider.SecurityGroupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SecurityGroupIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VPCID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VPCIDRef,
		Selector:     mg.Spec.InitProvider.VPCIDSelector,
		To: reference.To{
			List:    &VPCList{},
			Managed: &VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VPCID")
	}
	mg.Spec.InitProvider.VPCID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VPCIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Snapshot.
func (mg *Snapshot) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VolumeURI),
		Extract:      resource.ExtractParamPath("uri", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VolumeURIRef,
		Selector:     mg.Spec.ForProvider.VolumeURISelector,
		To: reference.To{
			List:    &BlockstorageList{},
			Managed: &Blockstorage{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VolumeURI")
	}
	mg.Spec.ForProvider.VolumeURI = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VolumeURIRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VolumeURI),
		Extract:      resource.ExtractParamPath("uri", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VolumeURIRef,
		Selector:     mg.Spec.InitProvider.VolumeURISelector,
		To: reference.To{
			List:    &BlockstorageList{},
			Managed: &Blockstorage{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VolumeURI")
	}
	mg.Spec.InitProvider.VolumeURI = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VolumeURIRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Subnet.
func (mg *Subnet) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VPCID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VPCIDRef,
		Selector:     mg.Spec.ForProvider.VPCIDSelector,
		To: reference.To{
			List:    &VPCList{},
			Managed: &VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VPCID")
	}
	mg.Spec.ForProvider.VPCID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VPCIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VPCID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VPCIDRef,
		Selector:     mg.Spec.InitProvider.VPCIDSelector,
		To: reference.To{
			List:    &VPCList{},
			Managed: &VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VPCID")
	}
	mg.Spec.InitProvider.VPCID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VPCIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this VPC.
func (mg *VPC) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Vpcpeering.
func (mg *Vpcpeering) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PeerVPC),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.PeerVPCRef,
		Selector:     mg.Spec.ForProvider.PeerVPCSelector,
		To: reference.To{
			List:    &VPCList{},
			Managed: &VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PeerVPC")
	}
	mg.Spec.ForProvider.PeerVPC = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PeerVPCRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VPCID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VPCIDRef,
		Selector:     mg.Spec.ForProvider.VPCIDSelector,
		To: reference.To{
			List:    &VPCList{},
			Managed: &VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VPCID")
	}
	mg.Spec.ForProvider.VPCID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VPCIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.PeerVPC),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.PeerVPCRef,
		Selector:     mg.Spec.InitProvider.PeerVPCSelector,
		To: reference.To{
			List:    &VPCList{},
			Managed: &VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PeerVPC")
	}
	mg.Spec.InitProvider.PeerVPC = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PeerVPCRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VPCID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VPCIDRef,
		Selector:     mg.Spec.InitProvider.VPCIDSelector,
		To: reference.To{
			List:    &VPCList{},
			Managed: &VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VPCID")
	}
	mg.Spec.InitProvider.VPCID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VPCIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Vpcpeeringroute.
func (mg *Vpcpeeringroute) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VPCID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VPCIDRef,
		Selector:     mg.Spec.ForProvider.VPCIDSelector,
		To: reference.To{
			List:    &VPCList{},
			Managed: &VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VPCID")
	}
	mg.Spec.ForProvider.VPCID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VPCIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VPCPeeringID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VPCPeeringIDRef,
		Selector:     mg.Spec.ForProvider.VPCPeeringIDSelector,
		To: reference.To{
			List:    &VpcpeeringList{},
			Managed: &Vpcpeering{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VPCPeeringID")
	}
	mg.Spec.ForProvider.VPCPeeringID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VPCPeeringIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VPCID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VPCIDRef,
		Selector:     mg.Spec.InitProvider.VPCIDSelector,
		To: reference.To{
			List:    &VPCList{},
			Managed: &VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VPCID")
	}
	mg.Spec.InitProvider.VPCID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VPCIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VPCPeeringID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VPCPeeringIDRef,
		Selector:     mg.Spec.InitProvider.VPCPeeringIDSelector,
		To: reference.To{
			List:    &VpcpeeringList{},
			Managed: &Vpcpeering{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VPCPeeringID")
	}
	mg.Spec.InitProvider.VPCPeeringID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VPCPeeringIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Vpnroute.
func (mg *Vpnroute) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VPNTunnelID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VPNTunnelIDRef,
		Selector:     mg.Spec.ForProvider.VPNTunnelIDSelector,
		To: reference.To{
			List:    &VpntunnelList{},
			Managed: &Vpntunnel{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VPNTunnelID")
	}
	mg.Spec.ForProvider.VPNTunnelID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VPNTunnelIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VPNTunnelID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VPNTunnelIDRef,
		Selector:     mg.Spec.InitProvider.VPNTunnelIDSelector,
		To: reference.To{
			List:    &VpntunnelList{},
			Managed: &Vpntunnel{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VPNTunnelID")
	}
	mg.Spec.InitProvider.VPNTunnelID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VPNTunnelIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Vpntunnel.
func (mg *Vpntunnel) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	if mg.Spec.ForProvider.Properties != nil {
		if mg.Spec.ForProvider.Properties.IPConfigurations != nil {
			if mg.Spec.ForProvider.Properties.IPConfigurations.PublicIP != nil {
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Properties.IPConfigurations.PublicIP.ID),
					Extract:      reference.ExternalName(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.Properties.IPConfigurations.PublicIP.IDRef,
					Selector:     mg.Spec.ForProvider.Properties.IPConfigurations.PublicIP.IDSelector,
					To: reference.To{
						List:    &ElasticipList{},
						Managed: &Elasticip{},
					},
				})
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.Properties.IPConfigurations.PublicIP.ID")
				}
				mg.Spec.ForProvider.Properties.IPConfigurations.PublicIP.ID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.Properties.IPConfigurations.PublicIP.IDRef = rsp.ResolvedReference

			}
		}
	}
	if mg.Spec.ForProvider.Properties != nil {
		if mg.Spec.ForProvider.Properties.IPConfigurations != nil {
			if mg.Spec.ForProvider.Properties.IPConfigurations.Subnet != nil {
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Properties.IPConfigurations.Subnet.ID),
					Extract:      reference.ExternalName(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.Properties.IPConfigurations.Subnet.IDRef,
					Selector:     mg.Spec.ForProvider.Properties.IPConfigurations.Subnet.IDSelector,
					To: reference.To{
						List:    &SubnetList{},
						Managed: &Subnet{},
					},
				})
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.Properties.IPConfigurations.Subnet.ID")
				}
				mg.Spec.ForProvider.Properties.IPConfigurations.Subnet.ID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.Properties.IPConfigurations.Subnet.IDRef = rsp.ResolvedReference

			}
		}
	}
	if mg.Spec.ForProvider.Properties != nil {
		if mg.Spec.ForProvider.Properties.IPConfigurations != nil {
			if mg.Spec.ForProvider.Properties.IPConfigurations.VPC != nil {
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Properties.IPConfigurations.VPC.ID),
					Extract:      reference.ExternalName(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.Properties.IPConfigurations.VPC.IDRef,
					Selector:     mg.Spec.ForProvider.Properties.IPConfigurations.VPC.IDSelector,
					To: reference.To{
						List:    &VPCList{},
						Managed: &VPC{},
					},
				})
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.Properties.IPConfigurations.VPC.ID")
				}
				mg.Spec.ForProvider.Properties.IPConfigurations.VPC.ID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.Properties.IPConfigurations.VPC.IDRef = rsp.ResolvedReference

			}
		}
	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &ProjectList{},
			Managed: &Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	if mg.Spec.InitProvider.Properties != nil {
		if mg.Spec.InitProvider.Properties.IPConfigurations != nil {
			if mg.Spec.InitProvider.Properties.IPConfigurations.PublicIP != nil {
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Properties.IPConfigurations.PublicIP.ID),
					Extract:      reference.ExternalName(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.Properties.IPConfigurations.PublicIP.IDRef,
					Selector:     mg.Spec.InitProvider.Properties.IPConfigurations.PublicIP.IDSelector,
					To: reference.To{
						List:    &ElasticipList{},
						Managed: &Elasticip{},
					},
				})
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.Properties.IPConfigurations.PublicIP.ID")
				}
				mg.Spec.InitProvider.Properties.IPConfigurations.PublicIP.ID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.Properties.IPConfigurations.PublicIP.IDRef = rsp.ResolvedReference

			}
		}
	}
	if mg.Spec.InitProvider.Properties != nil {
		if mg.Spec.InitProvider.Properties.IPConfigurations != nil {
			if mg.Spec.InitProvider.Properties.IPConfigurations.Subnet != nil {
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Properties.IPConfigurations.Subnet.ID),
					Extract:      reference.ExternalName(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.Properties.IPConfigurations.Subnet.IDRef,
					Selector:     mg.Spec.InitProvider.Properties.IPConfigurations.Subnet.IDSelector,
					To: reference.To{
						List:    &SubnetList{},
						Managed: &Subnet{},
					},
				})
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.Properties.IPConfigurations.Subnet.ID")
				}
				mg.Spec.InitProvider.Properties.IPConfigurations.Subnet.ID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.Properties.IPConfigurations.Subnet.IDRef = rsp.ResolvedReference

			}
		}
	}
	if mg.Spec.InitProvider.Properties != nil {
		if mg.Spec.InitProvider.Properties.IPConfigurations != nil {
			if mg.Spec.InitProvider.Properties.IPConfigurations.VPC != nil {
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Properties.IPConfigurations.VPC.ID),
					Extract:      reference.ExternalName(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.Properties.IPConfigurations.VPC.IDRef,
					Selector:     mg.Spec.InitProvider.Properties.IPConfigurations.VPC.IDSelector,
					To: reference.To{
						List:    &VPCList{},
						Managed: &VPC{},
					},
				})
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.Properties.IPConfigurations.VPC.ID")
				}
				mg.Spec.InitProvider.Properties.IPConfigurations.VPC.ID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.Properties.IPConfigurations.VPC.IDRef = rsp.ResolvedReference

			}
		}
	}

	return nil
}
