// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Backup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Blockstorage) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Cloudserver) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Containerregistry) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Database) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Databasebackup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Databasegrant) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Dbaas) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Dbaasuser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Elasticip) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Kaas) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Keypair) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *KMS) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Project) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Restore) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Schedulejob) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Securitygroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Securityrule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Snapshot) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Subnet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VPC) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Vpcpeering) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Vpcpeeringroute) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Vpnroute) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Vpntunnel) Hub() {}
