// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type KeypairInitParameters struct {

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// created.)
	// Display name for the KeyPair. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// format public key string (e.g., ssh-rsa AAAA...). The provider uploads this to ArubaCloud; the corresponding private key is never stored. Write-only — this value is sent to the API but is not returned in subsequent read responses. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// OpenSSH-format public key string (e.g., `ssh-rsa AAAA...`). The provider uploads this to ArubaCloud; the corresponding private key is never stored. Write-only — this value is sent to the API but is not returned in subsequent read responses. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ValueSecretRef v2.LocalSecretKeySelector `json:"valueSecretRef" tf:"-"`
}

type KeypairObservation struct {

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// created.)
	// Display name for the KeyPair. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a *_uri_ref attribute).
	// Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a `*_uri_ref` attribute).
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

type KeypairParameters struct {

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// created.)
	// Display name for the KeyPair. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// format public key string (e.g., ssh-rsa AAAA...). The provider uploads this to ArubaCloud; the corresponding private key is never stored. Write-only — this value is sent to the API but is not returned in subsequent read responses. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// OpenSSH-format public key string (e.g., `ssh-rsa AAAA...`). The provider uploads this to ArubaCloud; the corresponding private key is never stored. Write-only — this value is sent to the API but is not returned in subsequent read responses. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Optional
	ValueSecretRef v2.LocalSecretKeySelector `json:"valueSecretRef" tf:"-"`
}

// KeypairSpec defines the desired state of Keypair
type KeypairSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            KeypairParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KeypairInitParameters `json:"initProvider,omitempty"`
}

// KeypairStatus defines the observed state of Keypair.
type KeypairStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               KeypairObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Keypair is the Schema for the Keypairs API. Manages an ArubaCloud SSH KeyPair.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type Keypair struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.valueSecretRef)",message="spec.forProvider.valueSecretRef is a required parameter"
	Spec   KeypairSpec   `json:"spec"`
	Status KeypairStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KeypairList contains a list of Keypairs
type KeypairList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Keypair `json:"items"`
}

// Repository type metadata.
var (
	Keypair_Kind             = "Keypair"
	Keypair_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Keypair_Kind}.String()
	Keypair_KindAPIVersion   = Keypair_Kind + "." + CRDGroupVersion.String()
	Keypair_GroupVersionKind = CRDGroupVersion.WithKind(Keypair_Kind)
)

func init() {
	SchemeBuilder.Register(&Keypair{}, &KeypairList{})
}
