// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type KaasInitParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the KaaS cluster.
	// Display name for the KaaS cluster.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the KaaS cluster. (see below for nested schema)
	Network *KaasNetworkInitParameters `json:"network,omitempty" tf:"network,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// pool configuration. (see below for nested schema)
	Settings *KaasSettingsInitParameters `json:"settings,omitempty" tf:"settings,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type KaasNetworkInitParameters struct {

	// (Attributes) CIDR block assigned to cluster nodes. (see below for nested schema)
	NodeCidr *NodeCidrInitParameters `json:"nodeCidr,omitempty" tf:"node_cidr,omitempty"`

	// (String) CIDR block used for pod networking within the cluster (e.g., 10.0.3.0/24).
	// CIDR block used for pod networking within the cluster (e.g., `10.0.3.0/24`).
	PodCidr *string `json:"podCidr,omitempty" tf:"pod_cidr,omitempty"`

	// (String) Name of the security group applied to cluster nodes.
	// Name of the security group applied to cluster nodes.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Securitygroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	SecurityGroupName *string `json:"securityGroupName,omitempty" tf:"security_group_name,omitempty"`

	// Reference to a Securitygroup in arubacloud to populate securityGroupName.
	// +kubebuilder:validation:Optional
	SecurityGroupNameRef *v2.NamespacedReference `json:"securityGroupNameRef,omitempty" tf:"-"`

	// Selector for a Securitygroup in arubacloud to populate securityGroupName.
	// +kubebuilder:validation:Optional
	SecurityGroupNameSelector *v2.NamespacedSelector `json:"securityGroupNameSelector,omitempty" tf:"-"`

	// created.)
	// URI of the subnet within the VPC (e.g., `arubacloud_subnet.example.uri`). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	SubnetURIRef *string `json:"subnetUriRef,omitempty" tf:"subnet_uri_ref,omitempty"`

	// Reference to a Subnet in arubacloud to populate subnetUriRef.
	// +kubebuilder:validation:Optional
	SubnetURIRefRef *v2.NamespacedReference `json:"subnetUriRefRef,omitempty" tf:"-"`

	// Selector for a Subnet in arubacloud to populate subnetUriRef.
	// +kubebuilder:validation:Optional
	SubnetURIRefSelector *v2.NamespacedSelector `json:"subnetUriRefSelector,omitempty" tf:"-"`

	// created.)
	// URI of the VPC that hosts the cluster (e.g., `arubacloud_vpc.example.uri`). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.VPC
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`

	// Reference to a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefRef *v2.NamespacedReference `json:"vpcUriRefRef,omitempty" tf:"-"`

	// Selector for a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefSelector *v2.NamespacedSelector `json:"vpcUriRefSelector,omitempty" tf:"-"`
}

type KaasNetworkObservation struct {

	// (Attributes) CIDR block assigned to cluster nodes. (see below for nested schema)
	NodeCidr *NodeCidrObservation `json:"nodeCidr,omitempty" tf:"node_cidr,omitempty"`

	// (String) CIDR block used for pod networking within the cluster (e.g., 10.0.3.0/24).
	// CIDR block used for pod networking within the cluster (e.g., `10.0.3.0/24`).
	PodCidr *string `json:"podCidr,omitempty" tf:"pod_cidr,omitempty"`

	// (String) Name of the security group applied to cluster nodes.
	// Name of the security group applied to cluster nodes.
	SecurityGroupName *string `json:"securityGroupName,omitempty" tf:"security_group_name,omitempty"`

	// created.)
	// URI of the subnet within the VPC (e.g., `arubacloud_subnet.example.uri`). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	SubnetURIRef *string `json:"subnetUriRef,omitempty" tf:"subnet_uri_ref,omitempty"`

	// created.)
	// URI of the VPC that hosts the cluster (e.g., `arubacloud_vpc.example.uri`). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`
}

type KaasNetworkParameters struct {

	// (Attributes) CIDR block assigned to cluster nodes. (see below for nested schema)
	// +kubebuilder:validation:Optional
	NodeCidr *NodeCidrParameters `json:"nodeCidr" tf:"node_cidr,omitempty"`

	// (String) CIDR block used for pod networking within the cluster (e.g., 10.0.3.0/24).
	// CIDR block used for pod networking within the cluster (e.g., `10.0.3.0/24`).
	// +kubebuilder:validation:Optional
	PodCidr *string `json:"podCidr,omitempty" tf:"pod_cidr,omitempty"`

	// (String) Name of the security group applied to cluster nodes.
	// Name of the security group applied to cluster nodes.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Securitygroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +kubebuilder:validation:Optional
	SecurityGroupName *string `json:"securityGroupName,omitempty" tf:"security_group_name,omitempty"`

	// Reference to a Securitygroup in arubacloud to populate securityGroupName.
	// +kubebuilder:validation:Optional
	SecurityGroupNameRef *v2.NamespacedReference `json:"securityGroupNameRef,omitempty" tf:"-"`

	// Selector for a Securitygroup in arubacloud to populate securityGroupName.
	// +kubebuilder:validation:Optional
	SecurityGroupNameSelector *v2.NamespacedSelector `json:"securityGroupNameSelector,omitempty" tf:"-"`

	// created.)
	// URI of the subnet within the VPC (e.g., `arubacloud_subnet.example.uri`). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	SubnetURIRef *string `json:"subnetUriRef,omitempty" tf:"subnet_uri_ref,omitempty"`

	// Reference to a Subnet in arubacloud to populate subnetUriRef.
	// +kubebuilder:validation:Optional
	SubnetURIRefRef *v2.NamespacedReference `json:"subnetUriRefRef,omitempty" tf:"-"`

	// Selector for a Subnet in arubacloud to populate subnetUriRef.
	// +kubebuilder:validation:Optional
	SubnetURIRefSelector *v2.NamespacedSelector `json:"subnetUriRefSelector,omitempty" tf:"-"`

	// created.)
	// URI of the VPC that hosts the cluster (e.g., `arubacloud_vpc.example.uri`). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.VPC
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("uri",true)
	// +kubebuilder:validation:Optional
	VPCURIRef *string `json:"vpcUriRef,omitempty" tf:"vpc_uri_ref,omitempty"`

	// Reference to a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefRef *v2.NamespacedReference `json:"vpcUriRefRef,omitempty" tf:"-"`

	// Selector for a VPC in arubacloud to populate vpcUriRef.
	// +kubebuilder:validation:Optional
	VPCURIRefSelector *v2.NamespacedSelector `json:"vpcUriRefSelector,omitempty" tf:"-"`
}

type KaasObservation struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Computed by the API. Management IP address of the cluster control plane, available once the cluster is active.
	// Computed by the API. Management IP address of the cluster control plane, available once the cluster is active.
	ManagementIP *string `json:"managementIp,omitempty" tf:"management_ip,omitempty"`

	// (String) Display name for the KaaS cluster.
	// Display name for the KaaS cluster.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the KaaS cluster. (see below for nested schema)
	Network *KaasNetworkObservation `json:"network,omitempty" tf:"network,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// pool configuration. (see below for nested schema)
	Settings *KaasSettingsObservation `json:"settings,omitempty" tf:"settings,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources.
	// Computed by the API. Full resource URI used as a reference value in other resources.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

type KaasParameters struct {

	// (String) Billing cycle. Accepted values: Hour, Month, Year.
	// Billing cycle. Accepted values: `Hour`, `Month`, `Year`.
	// +kubebuilder:validation:Optional
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// Bergamo). See the available locations and zones. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// Region identifier (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center). (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the KaaS cluster.
	// Display name for the KaaS cluster.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Network configuration for the KaaS cluster. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Network *KaasNetworkParameters `json:"network,omitempty" tf:"network,omitempty"`

	// created.)
	// ID of the project that owns this resource. (Immutable — changing this value forces the resource to be destroyed and re-created.)
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// pool configuration. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Settings *KaasSettingsParameters `json:"settings,omitempty" tf:"settings,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type KaasSettingsInitParameters struct {

	// availability mode.
	// When `true`, the control plane is deployed in high-availability mode.
	Ha *bool `json:"ha,omitempty" tf:"ha,omitempty"`

	// (String) Kubernetes version string (e.g., 1.28). Available versions are listed in the ArubaCloud metadata API.
	// Kubernetes version string (e.g., `1.28`). Available versions are listed in the ArubaCloud metadata API.
	KubernetesVersion *string `json:"kubernetesVersion,omitempty" tf:"kubernetes_version,omitempty"`

	// (Attributes List) One or more node pools that make up the cluster worker fleet. (see below for nested schema)
	NodePools []NodePoolsInitParameters `json:"nodePools,omitempty" tf:"node_pools,omitempty"`
}

type KaasSettingsObservation struct {

	// availability mode.
	// When `true`, the control plane is deployed in high-availability mode.
	Ha *bool `json:"ha,omitempty" tf:"ha,omitempty"`

	// (String) Kubernetes version string (e.g., 1.28). Available versions are listed in the ArubaCloud metadata API.
	// Kubernetes version string (e.g., `1.28`). Available versions are listed in the ArubaCloud metadata API.
	KubernetesVersion *string `json:"kubernetesVersion,omitempty" tf:"kubernetes_version,omitempty"`

	// (Attributes List) One or more node pools that make up the cluster worker fleet. (see below for nested schema)
	NodePools []NodePoolsObservation `json:"nodePools,omitempty" tf:"node_pools,omitempty"`
}

type KaasSettingsParameters struct {

	// availability mode.
	// When `true`, the control plane is deployed in high-availability mode.
	// +kubebuilder:validation:Optional
	Ha *bool `json:"ha,omitempty" tf:"ha,omitempty"`

	// (String) Kubernetes version string (e.g., 1.28). Available versions are listed in the ArubaCloud metadata API.
	// Kubernetes version string (e.g., `1.28`). Available versions are listed in the ArubaCloud metadata API.
	// +kubebuilder:validation:Optional
	KubernetesVersion *string `json:"kubernetesVersion" tf:"kubernetes_version,omitempty"`

	// (Attributes List) One or more node pools that make up the cluster worker fleet. (see below for nested schema)
	// +kubebuilder:validation:Optional
	NodePools []NodePoolsParameters `json:"nodePools" tf:"node_pools,omitempty"`
}

type NodeCidrInitParameters struct {

	// (String) Node CIDR address in CIDR notation (e.g., 10.0.0.0/24).
	// Node CIDR address in CIDR notation (e.g., `10.0.0.0/24`).
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) Display name for the KaaS cluster.
	// Human-readable label for the node CIDR block.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type NodeCidrObservation struct {

	// (String) Node CIDR address in CIDR notation (e.g., 10.0.0.0/24).
	// Node CIDR address in CIDR notation (e.g., `10.0.0.0/24`).
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) Display name for the KaaS cluster.
	// Human-readable label for the node CIDR block.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type NodeCidrParameters struct {

	// (String) Node CIDR address in CIDR notation (e.g., 10.0.0.0/24).
	// Node CIDR address in CIDR notation (e.g., `10.0.0.0/24`).
	// +kubebuilder:validation:Optional
	Address *string `json:"address" tf:"address,omitempty"`

	// (String) Display name for the KaaS cluster.
	// Human-readable label for the node CIDR block.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type NodePoolsInitParameters struct {

	// (Boolean) When true, the node pool scales automatically between min_count and max_count.
	// When `true`, the node pool scales automatically between `min_count` and `max_count`.
	Autoscaling *bool `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (String) Compute flavour for cluster nodes (e.g., CSO4A8). See available flavours.
	// Compute flavour for cluster nodes (e.g., `CSO4A8`). See [available flavours](https://api.arubacloud.com/docs/metadata/#cloudserver-flavors).
	Instance *string `json:"instance,omitempty" tf:"instance,omitempty"`

	// (Number) Maximum number of nodes when autoscaling is enabled.
	// Maximum number of nodes when autoscaling is enabled.
	MaxCount *float64 `json:"maxCount,omitempty" tf:"max_count,omitempty"`

	// (Number) Minimum number of nodes when autoscaling is enabled.
	// Minimum number of nodes when autoscaling is enabled.
	MinCount *float64 `json:"minCount,omitempty" tf:"min_count,omitempty"`

	// (String) Display name for the KaaS cluster.
	// Display name for the node pool.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Number of worker nodes in the cluster.
	// Number of worker nodes in the cluster.
	Nodes *float64 `json:"nodes,omitempty" tf:"nodes,omitempty"`

	// (String) Datacenter zone code where the node pool is deployed.
	// Datacenter zone code where the node pool is deployed.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type NodePoolsObservation struct {

	// (Boolean) When true, the node pool scales automatically between min_count and max_count.
	// When `true`, the node pool scales automatically between `min_count` and `max_count`.
	Autoscaling *bool `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (String) Compute flavour for cluster nodes (e.g., CSO4A8). See available flavours.
	// Compute flavour for cluster nodes (e.g., `CSO4A8`). See [available flavours](https://api.arubacloud.com/docs/metadata/#cloudserver-flavors).
	Instance *string `json:"instance,omitempty" tf:"instance,omitempty"`

	// (Number) Maximum number of nodes when autoscaling is enabled.
	// Maximum number of nodes when autoscaling is enabled.
	MaxCount *float64 `json:"maxCount,omitempty" tf:"max_count,omitempty"`

	// (Number) Minimum number of nodes when autoscaling is enabled.
	// Minimum number of nodes when autoscaling is enabled.
	MinCount *float64 `json:"minCount,omitempty" tf:"min_count,omitempty"`

	// (String) Display name for the KaaS cluster.
	// Display name for the node pool.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Number of worker nodes in the cluster.
	// Number of worker nodes in the cluster.
	Nodes *float64 `json:"nodes,omitempty" tf:"nodes,omitempty"`

	// (String) Datacenter zone code where the node pool is deployed.
	// Datacenter zone code where the node pool is deployed.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type NodePoolsParameters struct {

	// (Boolean) When true, the node pool scales automatically between min_count and max_count.
	// When `true`, the node pool scales automatically between `min_count` and `max_count`.
	// +kubebuilder:validation:Optional
	Autoscaling *bool `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (String) Compute flavour for cluster nodes (e.g., CSO4A8). See available flavours.
	// Compute flavour for cluster nodes (e.g., `CSO4A8`). See [available flavours](https://api.arubacloud.com/docs/metadata/#cloudserver-flavors).
	// +kubebuilder:validation:Optional
	Instance *string `json:"instance" tf:"instance,omitempty"`

	// (Number) Maximum number of nodes when autoscaling is enabled.
	// Maximum number of nodes when autoscaling is enabled.
	// +kubebuilder:validation:Optional
	MaxCount *float64 `json:"maxCount,omitempty" tf:"max_count,omitempty"`

	// (Number) Minimum number of nodes when autoscaling is enabled.
	// Minimum number of nodes when autoscaling is enabled.
	// +kubebuilder:validation:Optional
	MinCount *float64 `json:"minCount,omitempty" tf:"min_count,omitempty"`

	// (String) Display name for the KaaS cluster.
	// Display name for the node pool.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (Number) Number of worker nodes in the cluster.
	// Number of worker nodes in the cluster.
	// +kubebuilder:validation:Optional
	Nodes *float64 `json:"nodes" tf:"nodes,omitempty"`

	// (String) Datacenter zone code where the node pool is deployed.
	// Datacenter zone code where the node pool is deployed.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone" tf:"zone,omitempty"`
}

// KaasSpec defines the desired state of Kaas
type KaasSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            KaasParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KaasInitParameters `json:"initProvider,omitempty"`
}

// KaasStatus defines the observed state of Kaas.
type KaasStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               KaasObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Kaas is the Schema for the Kaass API. Manages an ArubaCloud Kubernetes cluster (KaaS — Kubernetes-as-a-Service).
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type Kaas struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.network) || (has(self.initProvider) && has(self.initProvider.network))",message="spec.forProvider.network is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.settings) || (has(self.initProvider) && has(self.initProvider.settings))",message="spec.forProvider.settings is a required parameter"
	Spec   KaasSpec   `json:"spec"`
	Status KaasStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KaasList contains a list of Kaass
type KaasList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Kaas `json:"items"`
}

// Repository type metadata.
var (
	Kaas_Kind             = "Kaas"
	Kaas_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Kaas_Kind}.String()
	Kaas_KindAPIVersion   = Kaas_Kind + "." + CRDGroupVersion.String()
	Kaas_GroupVersionKind = CRDGroupVersion.WithKind(Kaas_Kind)
)

func init() {
	SchemeBuilder.Register(&Kaas{}, &KaasList{})
}
