// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type VpnrouteInitParameters struct {

	// Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the VPN route.
	// Display name for the VPN route.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Attributes) Routing properties for the VPN route. (see below for nested schema)
	Properties *VpnroutePropertiesInitParameters `json:"properties,omitempty" tf:"properties,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) ID of the VPN tunnel this route is associated with.
	// ID of the VPN tunnel this route is associated with.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Vpntunnel
	VPNTunnelID *string `json:"vpnTunnelId,omitempty" tf:"vpn_tunnel_id,omitempty"`

	// Reference to a Vpntunnel in arubacloud to populate vpnTunnelId.
	// +kubebuilder:validation:Optional
	VPNTunnelIDRef *v2.NamespacedReference `json:"vpnTunnelIdRef,omitempty" tf:"-"`

	// Selector for a Vpntunnel in arubacloud to populate vpnTunnelId.
	// +kubebuilder:validation:Optional
	VPNTunnelIDSelector *v2.NamespacedSelector `json:"vpnTunnelIdSelector,omitempty" tf:"-"`
}

type VpnrouteObservation struct {

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the VPN route.
	// Display name for the VPN route.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) Routing properties for the VPN route. (see below for nested schema)
	Properties *VpnroutePropertiesObservation `json:"properties,omitempty" tf:"properties,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a *_uri_ref attribute).
	// Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a `*_uri_ref` attribute).
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// (String) ID of the VPN tunnel this route is associated with.
	// ID of the VPN tunnel this route is associated with.
	VPNTunnelID *string `json:"vpnTunnelId,omitempty" tf:"vpn_tunnel_id,omitempty"`
}

type VpnrouteParameters struct {

	// Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the VPN route.
	// Display name for the VPN route.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Attributes) Routing properties for the VPN route. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Properties *VpnroutePropertiesParameters `json:"properties,omitempty" tf:"properties,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) ID of the VPN tunnel this route is associated with.
	// ID of the VPN tunnel this route is associated with.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Vpntunnel
	// +kubebuilder:validation:Optional
	VPNTunnelID *string `json:"vpnTunnelId,omitempty" tf:"vpn_tunnel_id,omitempty"`

	// Reference to a Vpntunnel in arubacloud to populate vpnTunnelId.
	// +kubebuilder:validation:Optional
	VPNTunnelIDRef *v2.NamespacedReference `json:"vpnTunnelIdRef,omitempty" tf:"-"`

	// Selector for a Vpntunnel in arubacloud to populate vpnTunnelId.
	// +kubebuilder:validation:Optional
	VPNTunnelIDSelector *v2.NamespacedSelector `json:"vpnTunnelIdSelector,omitempty" tf:"-"`
}

type VpnroutePropertiesInitParameters struct {

	// side subnet to route over this tunnel (e.g., 10.0.1.0/24).
	// CIDR of the ArubaCloud-side subnet to route over this tunnel (e.g., `10.0.1.0/24`).
	CloudSubnet *string `json:"cloudSubnet,omitempty" tf:"cloud_subnet,omitempty"`

	// premises subnet reachable through this tunnel (e.g., 192.168.1.0/24).
	// CIDR of the on-premises subnet reachable through this tunnel (e.g., `192.168.1.0/24`).
	OnPremSubnet *string `json:"onPremSubnet,omitempty" tf:"on_prem_subnet,omitempty"`
}

type VpnroutePropertiesObservation struct {

	// side subnet to route over this tunnel (e.g., 10.0.1.0/24).
	// CIDR of the ArubaCloud-side subnet to route over this tunnel (e.g., `10.0.1.0/24`).
	CloudSubnet *string `json:"cloudSubnet,omitempty" tf:"cloud_subnet,omitempty"`

	// premises subnet reachable through this tunnel (e.g., 192.168.1.0/24).
	// CIDR of the on-premises subnet reachable through this tunnel (e.g., `192.168.1.0/24`).
	OnPremSubnet *string `json:"onPremSubnet,omitempty" tf:"on_prem_subnet,omitempty"`
}

type VpnroutePropertiesParameters struct {

	// side subnet to route over this tunnel (e.g., 10.0.1.0/24).
	// CIDR of the ArubaCloud-side subnet to route over this tunnel (e.g., `10.0.1.0/24`).
	// +kubebuilder:validation:Optional
	CloudSubnet *string `json:"cloudSubnet" tf:"cloud_subnet,omitempty"`

	// premises subnet reachable through this tunnel (e.g., 192.168.1.0/24).
	// CIDR of the on-premises subnet reachable through this tunnel (e.g., `192.168.1.0/24`).
	// +kubebuilder:validation:Optional
	OnPremSubnet *string `json:"onPremSubnet" tf:"on_prem_subnet,omitempty"`
}

// VpnrouteSpec defines the desired state of Vpnroute
type VpnrouteSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VpnrouteParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VpnrouteInitParameters `json:"initProvider,omitempty"`
}

// VpnrouteStatus defines the observed state of Vpnroute.
type VpnrouteStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               VpnrouteObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Vpnroute is the Schema for the Vpnroutes API. Manages a static route associated with an ArubaCloud VPN Tunnel.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type Vpnroute struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.properties) || (has(self.initProvider) && has(self.initProvider.properties))",message="spec.forProvider.properties is a required parameter"
	Spec   VpnrouteSpec   `json:"spec"`
	Status VpnrouteStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VpnrouteList contains a list of Vpnroutes
type VpnrouteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Vpnroute `json:"items"`
}

// Repository type metadata.
var (
	Vpnroute_Kind             = "Vpnroute"
	Vpnroute_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Vpnroute_Kind}.String()
	Vpnroute_KindAPIVersion   = Vpnroute_Kind + "." + CRDGroupVersion.String()
	Vpnroute_GroupVersionKind = CRDGroupVersion.WithKind(Vpnroute_Kind)
)

func init() {
	SchemeBuilder.Register(&Vpnroute{}, &VpnrouteList{})
}
