// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type VpcpeeringInitParameters struct {

	// Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the VPC peering.
	// Display name for the VPC peering.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID or URI of the remote peer VPC to connect to.
	// ID or URI of the remote peer VPC to connect to.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.VPC
	PeerVPC *string `json:"peerVpc,omitempty" tf:"peer_vpc,omitempty"`

	// Reference to a VPC in arubacloud to populate peerVpc.
	// +kubebuilder:validation:Optional
	PeerVPCRef *v2.NamespacedReference `json:"peerVpcRef,omitempty" tf:"-"`

	// Selector for a VPC in arubacloud to populate peerVpc.
	// +kubebuilder:validation:Optional
	PeerVPCSelector *v2.NamespacedSelector `json:"peerVpcSelector,omitempty" tf:"-"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) ID of the local VPC initiating this peering connection.
	// ID of the local VPC initiating this peering connection.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.VPC
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Reference to a VPC in arubacloud to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDRef *v2.NamespacedReference `json:"vpcIdRef,omitempty" tf:"-"`

	// Selector for a VPC in arubacloud to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDSelector *v2.NamespacedSelector `json:"vpcIdSelector,omitempty" tf:"-"`
}

type VpcpeeringObservation struct {

	// (String) Computed by the API. Unique identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the VPC peering.
	// Display name for the VPC peering.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID or URI of the remote peer VPC to connect to.
	// ID or URI of the remote peer VPC to connect to.
	PeerVPC *string `json:"peerVpc,omitempty" tf:"peer_vpc,omitempty"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a *_uri_ref attribute).
	// Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a `*_uri_ref` attribute).
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// (String) ID of the local VPC initiating this peering connection.
	// ID of the local VPC initiating this peering connection.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type VpcpeeringParameters struct {

	// Bergamo). See the available locations and zones.
	// Region identifier for the resource (e.g., `ITBG-Bergamo`). See the [available locations and zones](https://api.arubacloud.com/docs/metadata/#location-and-data-center).
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Display name for the VPC peering.
	// Display name for the VPC peering.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ID or URI of the remote peer VPC to connect to.
	// ID or URI of the remote peer VPC to connect to.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.VPC
	// +kubebuilder:validation:Optional
	PeerVPC *string `json:"peerVpc,omitempty" tf:"peer_vpc,omitempty"`

	// Reference to a VPC in arubacloud to populate peerVpc.
	// +kubebuilder:validation:Optional
	PeerVPCRef *v2.NamespacedReference `json:"peerVpcRef,omitempty" tf:"-"`

	// Selector for a VPC in arubacloud to populate peerVpc.
	// +kubebuilder:validation:Optional
	PeerVPCSelector *v2.NamespacedSelector `json:"peerVpcSelector,omitempty" tf:"-"`

	// (String) ID of the project that owns this resource.
	// ID of the project that owns this resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (List of String) List of string tags attached to the resource for filtering and organisation.
	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// resource timeout override (e.g. "15m", "1h"). Overrides the provider-level resource_timeout for this resource's Create and Delete operations. Uses Go duration syntax.
	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) ID of the local VPC initiating this peering connection.
	// ID of the local VPC initiating this peering connection.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.VPC
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Reference to a VPC in arubacloud to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDRef *v2.NamespacedReference `json:"vpcIdRef,omitempty" tf:"-"`

	// Selector for a VPC in arubacloud to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDSelector *v2.NamespacedSelector `json:"vpcIdSelector,omitempty" tf:"-"`
}

// VpcpeeringSpec defines the desired state of Vpcpeering
type VpcpeeringSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VpcpeeringParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VpcpeeringInitParameters `json:"initProvider,omitempty"`
}

// VpcpeeringStatus defines the observed state of Vpcpeering.
type VpcpeeringStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               VpcpeeringObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Vpcpeering is the Schema for the Vpcpeerings API. Manages an ArubaCloud VPC Peering connection between two VPCs, enabling private routing between them.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type Vpcpeering struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   VpcpeeringSpec   `json:"spec"`
	Status VpcpeeringStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VpcpeeringList contains a list of Vpcpeerings
type VpcpeeringList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Vpcpeering `json:"items"`
}

// Repository type metadata.
var (
	Vpcpeering_Kind             = "Vpcpeering"
	Vpcpeering_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Vpcpeering_Kind}.String()
	Vpcpeering_KindAPIVersion   = Vpcpeering_Kind + "." + CRDGroupVersion.String()
	Vpcpeering_GroupVersionKind = CRDGroupVersion.WithKind(Vpcpeering_Kind)
)

func init() {
	SchemeBuilder.Register(&Vpcpeering{}, &VpcpeeringList{})
}
