// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type VpcpeeringrouteInitParameters struct {

	// Billing cycle for the resource. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// Local network CIDR that is reachable on this side of the peering (e.g., `10.0.1.0/24`).
	LocalNetworkAddress *string `json:"localNetworkAddress,omitempty" tf:"local_network_address,omitempty"`

	// Display name for the VPC peering route.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of the project that owns this resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// Remote network CIDR reachable through the peering connection (e.g., `10.0.2.0/24`).
	RemoteNetworkAddress *string `json:"remoteNetworkAddress,omitempty" tf:"remote_network_address,omitempty"`

	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// ID of the VPC this peering route belongs to.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.VPC
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Reference to a VPC in arubacloud to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDRef *v2.NamespacedReference `json:"vpcIdRef,omitempty" tf:"-"`

	// Selector for a VPC in arubacloud to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDSelector *v2.NamespacedSelector `json:"vpcIdSelector,omitempty" tf:"-"`

	// ID of the VPC peering connection this route belongs to.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Vpcpeering
	VPCPeeringID *string `json:"vpcPeeringId,omitempty" tf:"vpc_peering_id,omitempty"`

	// Reference to a Vpcpeering in arubacloud to populate vpcPeeringId.
	// +kubebuilder:validation:Optional
	VPCPeeringIDRef *v2.NamespacedReference `json:"vpcPeeringIdRef,omitempty" tf:"-"`

	// Selector for a Vpcpeering in arubacloud to populate vpcPeeringId.
	// +kubebuilder:validation:Optional
	VPCPeeringIDSelector *v2.NamespacedSelector `json:"vpcPeeringIdSelector,omitempty" tf:"-"`
}

type VpcpeeringrouteObservation struct {

	// Billing cycle for the resource. Accepted values: `Hour`, `Month`, `Year`.
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Local network CIDR that is reachable on this side of the peering (e.g., `10.0.1.0/24`).
	LocalNetworkAddress *string `json:"localNetworkAddress,omitempty" tf:"local_network_address,omitempty"`

	// Display name for the VPC peering route.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of the project that owns this resource.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Remote network CIDR reachable through the peering connection (e.g., `10.0.2.0/24`).
	RemoteNetworkAddress *string `json:"remoteNetworkAddress,omitempty" tf:"remote_network_address,omitempty"`

	// List of string tags attached to the resource for filtering and organisation.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Computed by the API. Full resource URI used as a reference value in other resources (e.g., as a `*_uri_ref` attribute).
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`

	// ID of the VPC this peering route belongs to.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// ID of the VPC peering connection this route belongs to.
	VPCPeeringID *string `json:"vpcPeeringId,omitempty" tf:"vpc_peering_id,omitempty"`
}

type VpcpeeringrouteParameters struct {

	// Billing cycle for the resource. Accepted values: `Hour`, `Month`, `Year`.
	// +kubebuilder:validation:Optional
	BillingPeriod *string `json:"billingPeriod,omitempty" tf:"billing_period,omitempty"`

	// Local network CIDR that is reachable on this side of the peering (e.g., `10.0.1.0/24`).
	// +kubebuilder:validation:Optional
	LocalNetworkAddress *string `json:"localNetworkAddress,omitempty" tf:"local_network_address,omitempty"`

	// Display name for the VPC peering route.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of the project that owns this resource.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in arubacloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// Remote network CIDR reachable through the peering connection (e.g., `10.0.2.0/24`).
	// +kubebuilder:validation:Optional
	RemoteNetworkAddress *string `json:"remoteNetworkAddress,omitempty" tf:"remote_network_address,omitempty"`

	// List of string tags attached to the resource for filtering and organisation.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Per-resource timeout override (e.g. `"15m"`, `"1h"`). Overrides the provider-level `resource_timeout` for this resource's Create and Delete operations. Uses Go duration syntax.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// ID of the VPC this peering route belongs to.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.VPC
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Reference to a VPC in arubacloud to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDRef *v2.NamespacedReference `json:"vpcIdRef,omitempty" tf:"-"`

	// Selector for a VPC in arubacloud to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDSelector *v2.NamespacedSelector `json:"vpcIdSelector,omitempty" tf:"-"`

	// ID of the VPC peering connection this route belongs to.
	// +crossplane:generate:reference:type=github.com/arubacloud/provider-arubacloud/apis/arubacloud/v1alpha1.Vpcpeering
	// +kubebuilder:validation:Optional
	VPCPeeringID *string `json:"vpcPeeringId,omitempty" tf:"vpc_peering_id,omitempty"`

	// Reference to a Vpcpeering in arubacloud to populate vpcPeeringId.
	// +kubebuilder:validation:Optional
	VPCPeeringIDRef *v2.NamespacedReference `json:"vpcPeeringIdRef,omitempty" tf:"-"`

	// Selector for a Vpcpeering in arubacloud to populate vpcPeeringId.
	// +kubebuilder:validation:Optional
	VPCPeeringIDSelector *v2.NamespacedSelector `json:"vpcPeeringIdSelector,omitempty" tf:"-"`
}

// VpcpeeringrouteSpec defines the desired state of Vpcpeeringroute
type VpcpeeringrouteSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VpcpeeringrouteParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VpcpeeringrouteInitParameters `json:"initProvider,omitempty"`
}

// VpcpeeringrouteStatus defines the observed state of Vpcpeeringroute.
type VpcpeeringrouteStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               VpcpeeringrouteObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Vpcpeeringroute is the Schema for the Vpcpeeringroutes API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,arubacloud}
type Vpcpeeringroute struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.billingPeriod) || (has(self.initProvider) && has(self.initProvider.billingPeriod))",message="spec.forProvider.billingPeriod is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.localNetworkAddress) || (has(self.initProvider) && has(self.initProvider.localNetworkAddress))",message="spec.forProvider.localNetworkAddress is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.remoteNetworkAddress) || (has(self.initProvider) && has(self.initProvider.remoteNetworkAddress))",message="spec.forProvider.remoteNetworkAddress is a required parameter"
	Spec   VpcpeeringrouteSpec   `json:"spec"`
	Status VpcpeeringrouteStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VpcpeeringrouteList contains a list of Vpcpeeringroutes
type VpcpeeringrouteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Vpcpeeringroute `json:"items"`
}

// Repository type metadata.
var (
	Vpcpeeringroute_Kind             = "Vpcpeeringroute"
	Vpcpeeringroute_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Vpcpeeringroute_Kind}.String()
	Vpcpeeringroute_KindAPIVersion   = Vpcpeeringroute_Kind + "." + CRDGroupVersion.String()
	Vpcpeeringroute_GroupVersionKind = CRDGroupVersion.WithKind(Vpcpeeringroute_Kind)
)

func init() {
	SchemeBuilder.Register(&Vpcpeeringroute{}, &VpcpeeringrouteList{})
}
