apiVersion: arubacloud.crossplane.io/v1alpha1
kind: KMS
metadata:
  name: my-kms
  namespace: crossplane-system
spec:
  forProvider:
    name: my-kms
    billingPeriod: Hour
    tags:
      - crossplane
    projectIdRef:
      name: my-project
  providerConfigRef:
    name: default
