apiVersion: arubacloud.crossplane.io/v1alpha1
kind: Securitygroup
metadata:
  name: web-sg
  namespace: crossplane-system
spec:
  forProvider:
    name: web-sg
    location: ITBG-Bergamo
    tags:
      - crossplane
    projectIdRef:
      name: my-project
    vpcIdRef:
      name: main-vpc
  providerConfigRef:
    name: default
