apiVersion: arubacloud.crossplane.io/v1alpha1
kind: Vpnroute
metadata:
  name: vpn-route-10-0-0
  namespace: crossplane-system
spec:
  forProvider:
    name: vpn-route-10-0-0
    location: ITBG-Bergamo
    projectIdRef:
      name: my-project
    vpnTunnelIdRef:
      name: site-to-site-tunnel
    # destination REQUIRES VERIFICATION - check VPNRoute schema
    destination: "10.0.0.0/24"
  providerConfigRef:
    name: default
