apiVersion: arubacloud.crossplane.io/v1alpha1
kind: Vpntunnel
metadata:
  name: site-to-site-tunnel
  namespace: crossplane-system
spec:
  forProvider:
    name: site-to-site-tunnel
    location: ITBG-Bergamo
    tags:
      - crossplane
    projectIdRef:
      name: my-project
    properties:
      vpnType: Site-To-Site
      vpnClientProtocol: ikev2
      billingPeriod: Hour
      ipConfigurations:
        # VPN tunnel references by ID (not URI) inside ip_configurations.
        vpc:
          idRef:
            name: main-vpc
        subnet:
          idRef:
            name: private-subnet
        publicIp:
          idRef:
            name: web-eip
      vpnClientSettings:
        ike:
          encryption: AES256
          hash: SHA256
          pfs: group14
        esp:
          encryption: AES256
          hash: SHA256
          pfs: group14
        peerClientPublicIp: "1.2.3.4"
  providerConfigRef:
    name: default
